<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class ShieldSeeder extends Seeder
{
    public function run(): void
    {
        // Roles
        $admin   = Role::firstOrCreate(['name' => 'admin']);
        $manager = Role::firstOrCreate(['name' => 'manager']);
        $viewer  = Role::firstOrCreate(['name' => 'viewer']);

        // Ensure permissions are generated by Shield first:
        // php artisan shield:generate --panel=admin
        $allPerms = Permission::all();

        // Admin gets everything
        $admin->syncPermissions($allPerms);

        // Manager — customize to your app
        $managerPerms = Permission::whereIn('name', [
            'access_admin_panel',
            // Attendance resource perms (Shield generates exact names)
            'view_any_attendance',
            'view_attendance',
            'create_attendance',
            'update_attendance',
            // Employees (read-only example)
            'view_any_employee',
            'view_employee',
        ])->get();
        $manager->syncPermissions($managerPerms);

        // Viewer — read-only example
        $viewerPerms = Permission::whereIn('name', [
            'access_admin_panel',
            'view_any_attendance',
            'view_attendance',
        ])->get();
        $viewer->syncPermissions($viewerPerms);
    }
}
