// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

void ui_comp_container_backgroundcontainer_create_hook( lv_obj_t * comp)
{
}
