// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_TIMEINFORMATION_H
#define UI_SCREEN_TIMEINFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_timeinformation
extern void ui_screen_timeinformation_screen_init(void);
extern void ui_screen_timeinformation_screen_destroy(void);
extern lv_obj_t *ui_screen_timeinformation;
extern lv_obj_t *ui_timeinformation_container_syncbuttoncontainer;
extern void ui_event_timeinformation_button_syncbutton( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_button_syncbutton;
extern lv_obj_t *ui_timeinformation_label_syncicon;
extern lv_obj_t *ui_timeinformation_label_syncnow;
extern lv_obj_t *ui_timeinformation_container_mastertimecontainer;
extern lv_obj_t *ui_timeinformation_container_timeinfocontainer;
extern void ui_event_timeinformation_spinbox_timeinput( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_spinbox_timeinput;
extern lv_obj_t *ui_timeinformation_dropdown_ampm;
extern lv_obj_t *ui_timeinformation_container_mastertimezonecontainer;
extern lv_obj_t *ui_timeinformation_container_timezonecontainer;
extern lv_obj_t *ui_timeinformation_dropdown_timezone;
extern lv_obj_t *ui_timeinformation_container_ntpcontainer;
extern void ui_event_timeinformation_textarea_ntpinput( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_textarea_ntpinput;
extern lv_obj_t *ui_timeinformation_checkbox_servertime;
extern lv_obj_t *ui_timeinformation_container_cancelok;
extern void ui_event_timeinformation_button_cancelbutton( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_button_cancelbutton;
extern lv_obj_t *ui_timeinformation_label_cancellabel;
extern void ui_event_timeinformation_button_okbutton( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_button_okbutton;
extern lv_obj_t *ui_timeinformation_label_oklabel;
extern void ui_event_timeinformation_keyboard_timeinformationkeyboard( lv_event_t * e);
extern lv_obj_t *ui_timeinformation_keyboard_timeinformationkeyboard;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_TimeInformation;
extern lv_obj_t *ui_TimeInformation_Container_TimeInformation_Container_SyncButtonContainer;
extern lv_obj_t *ui_TimeInformation_Button_TimeInformation_Button_syncButton;
extern lv_obj_t *ui_TimeInformation_Label_TimeInformation_Label_SyncIcon;
extern lv_obj_t *ui_TimeInformation_Label_SyncNow;
extern lv_obj_t *ui_TimeInformation_Container_TimeInformation_Container_MasterTimeContainer;
extern lv_obj_t *ui_TimeInformation_Container_TimeInfoContainer;
extern lv_obj_t *ui_TimeInformation_Dropdown_TimeInformation_Dropdown_AMPM;
extern lv_obj_t *ui_TimeInformation_Container_TimeInformation_Container_MasterTimeZoneContainer;
extern lv_obj_t *ui_TimeInformation_Container_TimeInformation_Container_TimeZoneContainer;
extern lv_obj_t *ui_TimeInformation_Dropdown_TimeInformation_Dropdown_TimeZone;
extern lv_obj_t *ui_TimeInformation_Container_TimeInformation_Container_NTPContainer;
extern lv_obj_t *ui_ServerTime;
extern lv_obj_t *ui_TimeInformation_Container_CancelOk;
extern lv_obj_t *ui_TimeInformation_Button_CancelButton;
extern lv_obj_t *ui_TimeInformation_Label_TimeInformation_Label_CancelLabel;
extern lv_obj_t *ui_TimeInformation_Button_TimeInformation_Button_OkButton;
extern lv_obj_t *ui_TimeInformation_Label_TimeInformation_Label_OkLabel;
extern lv_obj_t *ui_TimeInformation_Keyboard_TimeInformationKeyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

