// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef _SQUARELINE_TIMECLOCK_RAND_UI_H
#define _SQUARELINE_TIMECLOCK_RAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_screen_mainscreen.h"
#include "ui_screen_adminlogin.h"
#include "ui_screen_setupconfigurations.h"
#include "ui_screen_networksetup.h"
#include "ui_screen_deviceinformation.h"
#include "ui_screen_timeinformation.h"
#include "ui_screen_serversetup.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui_startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_baseline_wifi_black_36dp_png);   // assets/baseline_wifi_black_36dp.png

// FONTS
LV_FONT_DECLARE( ui_font_Icon2);
LV_FONT_DECLARE( ui_font_Icons);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
