// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef _UI_COMP_BACKGROUNDCONTAINER_H
#define _UI_COMP_BACKGROUNDCONTAINER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BackGroundContainer
#define UI_COMP_BACKGROUNDCONTAINER_CONTAINER_BACKGROUNDCONTAINER 0
#define _UI_COMP_BACKGROUNDCONTAINER_NUM 1
lv_obj_t *ui_container_backgroundcontainer_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
