// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

// COMPONENT BackGroundContainer

lv_obj_t *ui_container_backgroundcontainer_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_container_backgroundcontainer;
cui_container_backgroundcontainer = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_container_backgroundcontainer);
lv_obj_set_width( cui_container_backgroundcontainer, 1024);
lv_obj_set_height( cui_container_backgroundcontainer, 600);
lv_obj_set_align( cui_container_backgroundcontainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_container_backgroundcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_container_backgroundcontainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_container_backgroundcontainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BACKGROUNDCONTAINER_NUM);
children[UI_COMP_BACKGROUNDCONTAINER_CONTAINER_BACKGROUNDCONTAINER] = cui_container_backgroundcontainer;
lv_obj_add_event_cb(cui_container_backgroundcontainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_container_backgroundcontainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_container_backgroundcontainer_create_hook(cui_container_backgroundcontainer);
return cui_container_backgroundcontainer; 
}

