// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

lv_obj_t *ui_ServerSetup_Label_CancelLabel;
lv_obj_t *ui_ServerSetup_Button_CancelButton;
lv_obj_t *ui_ServerSetup_Label_RegisterLabel;
lv_obj_t *ui_ServerSetup_Button_RegisterButton;
lv_obj_t *ui_ServerSetup_Label_TestConnectionLabel;
lv_obj_t *ui_ServerSetup_Button_TestConnectionButton;
lv_obj_t *ui_ServerSetup_Label_OkLabel;
lv_obj_t *ui_ServerSetup_Button_OkButton;
lv_obj_t *ui_ServerSetup_Container_CancelOk;
lv_obj_t *ui_ServerSetup_Textarea_DeviceIDInput;
lv_obj_t *ui_ServerSetup_Label_DeviceIDLabel;
lv_obj_t *ui_ServerSetup_Container_DeviceIDContainer;
lv_obj_t *ui_ServerSetup_Textarea_StatusInput;
lv_obj_t *ui_ServerSetup_Label_StatusLabel;
lv_obj_t *ui_ServerSetup_Container_StatusContainer;
lv_obj_t *ui_ServerSetup_Textarea_DeviceNameInput;
lv_obj_t *ui_ServerSetup_Label_DeviceNameLabel;
lv_obj_t *ui_ServerSetup_Container_DeviceNameContainer;
lv_obj_t *ui_ServerSetup_Textarea_PortInput;
lv_obj_t *ui_ServerSetup_Label_PortLabel;
lv_obj_t *ui_ServerSetup_Container_PortContainer;
lv_obj_t *ui_ServerSetup_Textarea_ServerURLInput;
lv_obj_t *ui_ServerSetup_Label_ServerURLLabel;
lv_obj_t *ui_ServerSetup_Container_ServerURLContainer;
lv_obj_t *ui_Screen_ServerSetup;
lv_obj_t *ui_screen_serversetup = NULL;lv_obj_t *ui_serversetup_backgroundcontainer_backgroundcontainer = NULL;lv_obj_t *ui_serversetup_container_serverurlcontainer = NULL;lv_obj_t *ui_serversetup_label_serverurllabel = NULL;lv_obj_t *ui_serversetup_textarea_serverurlinput = NULL;lv_obj_t *ui_serversetup_container_portcontainer = NULL;lv_obj_t *ui_serversetup_label_portlabel = NULL;lv_obj_t *ui_serversetup_textarea_portinput = NULL;lv_obj_t *ui_serversetup_container_devicenamecontainer = NULL;lv_obj_t *ui_serversetup_label_devicenamelabel = NULL;lv_obj_t *ui_serversetup_textarea_devicenameinput = NULL;lv_obj_t *ui_serversetup_container_statuscontainer = NULL;lv_obj_t *ui_serversetup_label_statuslabel = NULL;lv_obj_t *ui_serversetup_textarea_statusinput = NULL;lv_obj_t *ui_serversetup_container_deviceidcontainer = NULL;lv_obj_t *ui_serversetup_label_deviceidlabel = NULL;lv_obj_t *ui_serversetup_textarea_deviceidinput = NULL;lv_obj_t *ui_serversetup_container_cancelok = NULL;lv_obj_t *ui_serversetup_button_okbutton = NULL;lv_obj_t *ui_serversetup_label_oklabel = NULL;lv_obj_t *ui_serversetup_button_testconnectionbutton = NULL;lv_obj_t *ui_serversetup_label_testconnectionlabel = NULL;lv_obj_t *ui_serversetup_button_registerbutton = NULL;lv_obj_t *ui_serversetup_label_registerlabel = NULL;lv_obj_t *ui_serversetup_button_cancelbutton = NULL;lv_obj_t *ui_serversetup_label_cancellabel = NULL;
// event funtions
void ui_event_serversetup_button_okbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setupconfigurations, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_setupconfigurations_screen_init);
}
}

void ui_event_serversetup_button_testconnectionbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setupconfigurations, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_setupconfigurations_screen_init);
}
}

void ui_event_serversetup_button_registerbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setupconfigurations, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_setupconfigurations_screen_init);
}
}

void ui_event_serversetup_button_cancelbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_mainscreen_screen_init);
}
}

// build funtions

void ui_screen_serversetup_screen_init(void)
{
ui_screen_serversetup = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_serversetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_backgroundcontainer_backgroundcontainer = ui_container_backgroundcontainer_create(ui_screen_serversetup);
lv_obj_set_x( ui_serversetup_backgroundcontainer_backgroundcontainer, 0 );
lv_obj_set_y( ui_serversetup_backgroundcontainer_backgroundcontainer, 0 );
lv_obj_set_flex_flow(ui_serversetup_backgroundcontainer_backgroundcontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_serversetup_backgroundcontainer_backgroundcontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_serversetup_container_serverurlcontainer = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_serverurlcontainer);
lv_obj_set_width( ui_serversetup_container_serverurlcontainer, 800);
lv_obj_set_height( ui_serversetup_container_serverurlcontainer, 50);
lv_obj_set_align( ui_serversetup_container_serverurlcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_serversetup_container_serverurlcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_serverurlcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_serverurlcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_label_serverurllabel = lv_label_create(ui_serversetup_container_serverurlcontainer);
lv_obj_set_width( ui_serversetup_label_serverurllabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_serverurllabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_serverurllabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_serverurllabel,"Server URL:");
lv_obj_set_style_text_color(ui_serversetup_label_serverurllabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_serversetup_label_serverurllabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_label_serverurllabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_textarea_serverurlinput = lv_textarea_create(ui_serversetup_container_serverurlcontainer);
lv_obj_set_width( ui_serversetup_textarea_serverurlinput, 500);
lv_obj_set_height( ui_serversetup_textarea_serverurlinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_serversetup_textarea_serverurlinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_serversetup_textarea_serverurlinput,"Server.host.com or 1.1.1.1");

lv_obj_set_style_text_font(ui_serversetup_textarea_serverurlinput, &lv_font_montserrat_18, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_serverurlcontainer,0);
ui_serversetup_container_portcontainer = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_portcontainer);
lv_obj_set_width( ui_serversetup_container_portcontainer, 800);
lv_obj_set_height( ui_serversetup_container_portcontainer, 50);
lv_obj_set_align( ui_serversetup_container_portcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_serversetup_container_portcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_portcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_portcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_label_portlabel = lv_label_create(ui_serversetup_container_portcontainer);
lv_obj_set_width( ui_serversetup_label_portlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_portlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_portlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_portlabel,"Port:");
lv_obj_set_style_text_color(ui_serversetup_label_portlabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_serversetup_label_portlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_label_portlabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_textarea_portinput = lv_textarea_create(ui_serversetup_container_portcontainer);
lv_obj_set_width( ui_serversetup_textarea_portinput, 500);
lv_obj_set_height( ui_serversetup_textarea_portinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_serversetup_textarea_portinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_serversetup_textarea_portinput,"8080");
lv_obj_set_style_text_font(ui_serversetup_textarea_portinput, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_portcontainer,1);
ui_serversetup_container_devicenamecontainer = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_devicenamecontainer);
lv_obj_set_width( ui_serversetup_container_devicenamecontainer, 800);
lv_obj_set_height( ui_serversetup_container_devicenamecontainer, 50);
lv_obj_set_align( ui_serversetup_container_devicenamecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_serversetup_container_devicenamecontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_devicenamecontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_devicenamecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_label_devicenamelabel = lv_label_create(ui_serversetup_container_devicenamecontainer);
lv_obj_set_width( ui_serversetup_label_devicenamelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_devicenamelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_devicenamelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_devicenamelabel,"Device Name:");
lv_obj_set_style_text_color(ui_serversetup_label_devicenamelabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_serversetup_label_devicenamelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_label_devicenamelabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_textarea_devicenameinput = lv_textarea_create(ui_serversetup_container_devicenamecontainer);
lv_obj_set_width( ui_serversetup_textarea_devicenameinput, 500);
lv_obj_set_height( ui_serversetup_textarea_devicenameinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_serversetup_textarea_devicenameinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_serversetup_textarea_devicenameinput,"Screen Room Clock 21");
lv_obj_set_style_text_font(ui_serversetup_textarea_devicenameinput, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_devicenamecontainer,2);
ui_serversetup_container_statuscontainer = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_statuscontainer);
lv_obj_set_width( ui_serversetup_container_statuscontainer, 800);
lv_obj_set_height( ui_serversetup_container_statuscontainer, 50);
lv_obj_set_align( ui_serversetup_container_statuscontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_serversetup_container_statuscontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_statuscontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_statuscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_label_statuslabel = lv_label_create(ui_serversetup_container_statuscontainer);
lv_obj_set_width( ui_serversetup_label_statuslabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_statuslabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_statuslabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_statuslabel,"Status:");
lv_obj_set_style_text_color(ui_serversetup_label_statuslabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_serversetup_label_statuslabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_label_statuslabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_textarea_statusinput = lv_textarea_create(ui_serversetup_container_statuscontainer);
lv_obj_set_width( ui_serversetup_textarea_statusinput, 500);
lv_obj_set_height( ui_serversetup_textarea_statusinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_serversetup_textarea_statusinput, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_serversetup_textarea_statusinput, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_serversetup_textarea_statusinput, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_statuscontainer,3);
ui_serversetup_container_deviceidcontainer = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_deviceidcontainer);
lv_obj_set_width( ui_serversetup_container_deviceidcontainer, 800);
lv_obj_set_height( ui_serversetup_container_deviceidcontainer, 50);
lv_obj_set_align( ui_serversetup_container_deviceidcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_serversetup_container_deviceidcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_deviceidcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_deviceidcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_label_deviceidlabel = lv_label_create(ui_serversetup_container_deviceidcontainer);
lv_obj_set_width( ui_serversetup_label_deviceidlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_deviceidlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_deviceidlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_deviceidlabel,"Device ID:");
lv_obj_set_style_text_color(ui_serversetup_label_deviceidlabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_serversetup_label_deviceidlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_label_deviceidlabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_textarea_deviceidinput = lv_textarea_create(ui_serversetup_container_deviceidcontainer);
lv_obj_set_width( ui_serversetup_textarea_deviceidinput, 500);
lv_obj_set_height( ui_serversetup_textarea_deviceidinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_serversetup_textarea_deviceidinput, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_serversetup_textarea_deviceidinput, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_serversetup_textarea_deviceidinput, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_deviceidcontainer,4);
ui_serversetup_container_cancelok = lv_obj_create(ui_serversetup_backgroundcontainer_backgroundcontainer);
lv_obj_remove_style_all(ui_serversetup_container_cancelok);
lv_obj_set_width( ui_serversetup_container_cancelok, 924);
lv_obj_set_height( ui_serversetup_container_cancelok, 60);
lv_obj_set_x( ui_serversetup_container_cancelok, 4 );
lv_obj_set_y( ui_serversetup_container_cancelok, 511 );
lv_obj_set_align( ui_serversetup_container_cancelok, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_serversetup_container_cancelok,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_serversetup_container_cancelok, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_serversetup_container_cancelok, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_serversetup_button_okbutton = lv_button_create(ui_serversetup_container_cancelok);
lv_obj_set_width( ui_serversetup_button_okbutton, 100);
lv_obj_set_height( ui_serversetup_button_okbutton, 50);
lv_obj_set_align( ui_serversetup_button_okbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_serversetup_button_okbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_serversetup_button_okbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_serversetup_button_okbutton, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_serversetup_button_okbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_button_okbutton, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_label_oklabel = lv_label_create(ui_serversetup_button_okbutton);
lv_obj_set_width( ui_serversetup_label_oklabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_oklabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_oklabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_oklabel,"OK");
lv_obj_set_style_text_font(ui_serversetup_label_oklabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_button_testconnectionbutton = lv_button_create(ui_serversetup_container_cancelok);
lv_obj_set_width( ui_serversetup_button_testconnectionbutton, 100);
lv_obj_set_height( ui_serversetup_button_testconnectionbutton, 50);
lv_obj_set_align( ui_serversetup_button_testconnectionbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_serversetup_button_testconnectionbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_serversetup_button_testconnectionbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_serversetup_button_testconnectionbutton, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_serversetup_button_testconnectionbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_button_testconnectionbutton, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_label_testconnectionlabel = lv_label_create(ui_serversetup_button_testconnectionbutton);
lv_obj_set_width( ui_serversetup_label_testconnectionlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_testconnectionlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_testconnectionlabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_serversetup_label_testconnectionlabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_serversetup_label_testconnectionlabel,"Test");
lv_obj_set_style_text_font(ui_serversetup_label_testconnectionlabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_button_registerbutton = lv_button_create(ui_serversetup_container_cancelok);
lv_obj_set_width( ui_serversetup_button_registerbutton, 100);
lv_obj_set_height( ui_serversetup_button_registerbutton, 50);
lv_obj_set_align( ui_serversetup_button_registerbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_serversetup_button_registerbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_serversetup_button_registerbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_serversetup_button_registerbutton, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_serversetup_button_registerbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_serversetup_button_registerbutton, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_label_registerlabel = lv_label_create(ui_serversetup_button_registerbutton);
lv_obj_set_width( ui_serversetup_label_registerlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_registerlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_registerlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_registerlabel,"Register");
lv_obj_set_style_text_font(ui_serversetup_label_registerlabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_button_cancelbutton = lv_button_create(ui_serversetup_container_cancelok);
lv_obj_set_width( ui_serversetup_button_cancelbutton, 100);
lv_obj_set_height( ui_serversetup_button_cancelbutton, 50);
lv_obj_set_align( ui_serversetup_button_cancelbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_serversetup_button_cancelbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_serversetup_button_cancelbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_serversetup_button_cancelbutton, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_serversetup_button_cancelbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_serversetup_label_cancellabel = lv_label_create(ui_serversetup_button_cancelbutton);
lv_obj_set_width( ui_serversetup_label_cancellabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_serversetup_label_cancellabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_serversetup_label_cancellabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_serversetup_label_cancellabel,"Cancel");
lv_obj_set_style_text_font(ui_serversetup_label_cancellabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_serversetup_container_cancelok,5);
lv_obj_add_event_cb(ui_serversetup_button_okbutton, ui_event_serversetup_button_okbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_serversetup_button_testconnectionbutton, ui_event_serversetup_button_testconnectionbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_serversetup_button_registerbutton, ui_event_serversetup_button_registerbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_serversetup_button_cancelbutton, ui_event_serversetup_button_cancelbutton, LV_EVENT_ALL, NULL);
ui_Screen_ServerSetup = ui_screen_serversetup;
ui_ServerSetup_Container_ServerURLContainer = ui_serversetup_container_serverurlcontainer;
ui_ServerSetup_Label_ServerURLLabel = ui_serversetup_label_serverurllabel;
ui_ServerSetup_Textarea_ServerURLInput = ui_serversetup_textarea_serverurlinput;
ui_ServerSetup_Container_PortContainer = ui_serversetup_container_portcontainer;
ui_ServerSetup_Label_PortLabel = ui_serversetup_label_portlabel;
ui_ServerSetup_Textarea_PortInput = ui_serversetup_textarea_portinput;
ui_ServerSetup_Container_DeviceNameContainer = ui_serversetup_container_devicenamecontainer;
ui_ServerSetup_Label_DeviceNameLabel = ui_serversetup_label_devicenamelabel;
ui_ServerSetup_Textarea_DeviceNameInput = ui_serversetup_textarea_devicenameinput;
ui_ServerSetup_Container_StatusContainer = ui_serversetup_container_statuscontainer;
ui_ServerSetup_Label_StatusLabel = ui_serversetup_label_statuslabel;
ui_ServerSetup_Textarea_StatusInput = ui_serversetup_textarea_statusinput;
ui_ServerSetup_Container_DeviceIDContainer = ui_serversetup_container_deviceidcontainer;
ui_ServerSetup_Label_DeviceIDLabel = ui_serversetup_label_deviceidlabel;
ui_ServerSetup_Textarea_DeviceIDInput = ui_serversetup_textarea_deviceidinput;
ui_ServerSetup_Container_CancelOk = ui_serversetup_container_cancelok;
ui_ServerSetup_Button_OkButton = ui_serversetup_button_okbutton;
ui_ServerSetup_Label_OkLabel = ui_serversetup_label_oklabel;
ui_ServerSetup_Button_TestConnectionButton = ui_serversetup_button_testconnectionbutton;
ui_ServerSetup_Label_TestConnectionLabel = ui_serversetup_label_testconnectionlabel;
ui_ServerSetup_Button_RegisterButton = ui_serversetup_button_registerbutton;
ui_ServerSetup_Label_RegisterLabel = ui_serversetup_label_registerlabel;
ui_ServerSetup_Button_CancelButton = ui_serversetup_button_cancelbutton;
ui_ServerSetup_Label_CancelLabel = ui_serversetup_label_cancellabel;

}

void ui_screen_serversetup_screen_destroy(void)
{
   if (ui_screen_serversetup) lv_obj_del(ui_screen_serversetup);

// NULL screen variables
ui_Screen_ServerSetup= NULL;
ui_screen_serversetup= NULL;
ui_serversetup_backgroundcontainer_backgroundcontainer= NULL;
ui_ServerSetup_Container_ServerURLContainer= NULL;
ui_serversetup_container_serverurlcontainer= NULL;
ui_ServerSetup_Label_ServerURLLabel= NULL;
ui_serversetup_label_serverurllabel= NULL;
ui_ServerSetup_Textarea_ServerURLInput= NULL;
ui_serversetup_textarea_serverurlinput= NULL;
ui_ServerSetup_Container_PortContainer= NULL;
ui_serversetup_container_portcontainer= NULL;
ui_ServerSetup_Label_PortLabel= NULL;
ui_serversetup_label_portlabel= NULL;
ui_ServerSetup_Textarea_PortInput= NULL;
ui_serversetup_textarea_portinput= NULL;
ui_ServerSetup_Container_DeviceNameContainer= NULL;
ui_serversetup_container_devicenamecontainer= NULL;
ui_ServerSetup_Label_DeviceNameLabel= NULL;
ui_serversetup_label_devicenamelabel= NULL;
ui_ServerSetup_Textarea_DeviceNameInput= NULL;
ui_serversetup_textarea_devicenameinput= NULL;
ui_ServerSetup_Container_StatusContainer= NULL;
ui_serversetup_container_statuscontainer= NULL;
ui_ServerSetup_Label_StatusLabel= NULL;
ui_serversetup_label_statuslabel= NULL;
ui_ServerSetup_Textarea_StatusInput= NULL;
ui_serversetup_textarea_statusinput= NULL;
ui_ServerSetup_Container_DeviceIDContainer= NULL;
ui_serversetup_container_deviceidcontainer= NULL;
ui_ServerSetup_Label_DeviceIDLabel= NULL;
ui_serversetup_label_deviceidlabel= NULL;
ui_ServerSetup_Textarea_DeviceIDInput= NULL;
ui_serversetup_textarea_deviceidinput= NULL;
ui_ServerSetup_Container_CancelOk= NULL;
ui_serversetup_container_cancelok= NULL;
ui_ServerSetup_Button_OkButton= NULL;
ui_serversetup_button_okbutton= NULL;
ui_ServerSetup_Label_OkLabel= NULL;
ui_serversetup_label_oklabel= NULL;
ui_ServerSetup_Button_TestConnectionButton= NULL;
ui_serversetup_button_testconnectionbutton= NULL;
ui_ServerSetup_Label_TestConnectionLabel= NULL;
ui_serversetup_label_testconnectionlabel= NULL;
ui_ServerSetup_Button_RegisterButton= NULL;
ui_serversetup_button_registerbutton= NULL;
ui_ServerSetup_Label_RegisterLabel= NULL;
ui_serversetup_label_registerlabel= NULL;
ui_ServerSetup_Button_CancelButton= NULL;
ui_serversetup_button_cancelbutton= NULL;
ui_ServerSetup_Label_CancelLabel= NULL;
ui_serversetup_label_cancellabel= NULL;

}
