// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_SERVERSETUP_H
#define UI_SCREEN_SERVERSETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_serversetup
extern void ui_screen_serversetup_screen_init(void);
extern void ui_screen_serversetup_screen_destroy(void);
extern lv_obj_t *ui_screen_serversetup;
extern lv_obj_t *ui_serversetup_backgroundcontainer_backgroundcontainer;
extern lv_obj_t *ui_serversetup_container_serverurlcontainer;
extern lv_obj_t *ui_serversetup_label_serverurllabel;
extern lv_obj_t *ui_serversetup_textarea_serverurlinput;
extern lv_obj_t *ui_serversetup_container_portcontainer;
extern lv_obj_t *ui_serversetup_label_portlabel;
extern lv_obj_t *ui_serversetup_textarea_portinput;
extern lv_obj_t *ui_serversetup_container_devicenamecontainer;
extern lv_obj_t *ui_serversetup_label_devicenamelabel;
extern lv_obj_t *ui_serversetup_textarea_devicenameinput;
extern lv_obj_t *ui_serversetup_container_statuscontainer;
extern lv_obj_t *ui_serversetup_label_statuslabel;
extern lv_obj_t *ui_serversetup_textarea_statusinput;
extern lv_obj_t *ui_serversetup_container_deviceidcontainer;
extern lv_obj_t *ui_serversetup_label_deviceidlabel;
extern lv_obj_t *ui_serversetup_textarea_deviceidinput;
extern lv_obj_t *ui_serversetup_container_cancelok;
extern void ui_event_serversetup_button_okbutton( lv_event_t * e);
extern lv_obj_t *ui_serversetup_button_okbutton;
extern lv_obj_t *ui_serversetup_label_oklabel;
extern void ui_event_serversetup_button_testconnectionbutton( lv_event_t * e);
extern lv_obj_t *ui_serversetup_button_testconnectionbutton;
extern lv_obj_t *ui_serversetup_label_testconnectionlabel;
extern void ui_event_serversetup_button_registerbutton( lv_event_t * e);
extern lv_obj_t *ui_serversetup_button_registerbutton;
extern lv_obj_t *ui_serversetup_label_registerlabel;
extern void ui_event_serversetup_button_cancelbutton( lv_event_t * e);
extern lv_obj_t *ui_serversetup_button_cancelbutton;
extern lv_obj_t *ui_serversetup_label_cancellabel;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_ServerSetup;
extern lv_obj_t *ui_ServerSetup_Container_ServerURLContainer;
extern lv_obj_t *ui_ServerSetup_Label_ServerURLLabel;
extern lv_obj_t *ui_ServerSetup_Textarea_ServerURLInput;
extern lv_obj_t *ui_ServerSetup_Container_PortContainer;
extern lv_obj_t *ui_ServerSetup_Label_PortLabel;
extern lv_obj_t *ui_ServerSetup_Textarea_PortInput;
extern lv_obj_t *ui_ServerSetup_Container_DeviceNameContainer;
extern lv_obj_t *ui_ServerSetup_Label_DeviceNameLabel;
extern lv_obj_t *ui_ServerSetup_Textarea_DeviceNameInput;
extern lv_obj_t *ui_ServerSetup_Container_StatusContainer;
extern lv_obj_t *ui_ServerSetup_Label_StatusLabel;
extern lv_obj_t *ui_ServerSetup_Textarea_StatusInput;
extern lv_obj_t *ui_ServerSetup_Container_DeviceIDContainer;
extern lv_obj_t *ui_ServerSetup_Label_DeviceIDLabel;
extern lv_obj_t *ui_ServerSetup_Textarea_DeviceIDInput;
extern lv_obj_t *ui_ServerSetup_Container_CancelOk;
extern lv_obj_t *ui_ServerSetup_Button_OkButton;
extern lv_obj_t *ui_ServerSetup_Label_OkLabel;
extern lv_obj_t *ui_ServerSetup_Button_TestConnectionButton;
extern lv_obj_t *ui_ServerSetup_Label_TestConnectionLabel;
extern lv_obj_t *ui_ServerSetup_Button_RegisterButton;
extern lv_obj_t *ui_ServerSetup_Label_RegisterLabel;
extern lv_obj_t *ui_ServerSetup_Button_CancelButton;
extern lv_obj_t *ui_ServerSetup_Label_CancelLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

