// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_textarea(lv_event_t * e);
void ui_event_keyboard_close(lv_event_t * e);
void ui_event_sync_now(lv_event_t * e);
void ui_event_server_test(lv_event_t * e);
void ui_event_server_register(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
