// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EmployeeInfo(lv_event_t * e);
void PunchInfo(lv_event_t * e);
void ui_event_textarea(lv_event_t * e);
void ui_event_keyboard_close(lv_event_t * e);
void ui_event_sync_now(lv_event_t * e);
void ui_event_server_test(lv_event_t * e);
void ui_event_server_register(lv_event_t * e);
void ui_event_save_time_settings(lv_event_t * e);

// Clock status types for the ClockStatusInput field
typedef enum {
    CLOCK_STATUS_OK = 0,           // All good - clear status
    CLOCK_STATUS_SERVER_OFFLINE,   // Server unreachable
    CLOCK_STATUS_NOT_REGISTERED,   // Device not registered
    CLOCK_STATUS_NOT_AUTHORIZED,   // Device pending approval or rejected
    CLOCK_STATUS_SUSPENDED,        // Device suspended by admin
} clock_status_t;

// Clock status display functions (uses ClockStatusInput field on MainScreen)
void ui_set_clock_status(clock_status_t status, const char *device_name);
clock_status_t ui_get_clock_status(void);

// Legacy server offline alert functions (now use ClockStatusInput)
void ui_show_server_offline_alert(void);
void ui_hide_server_offline_alert(void);

// Punch display helpers
void ui_show_employee_info(const char *employee_name);
void ui_show_punch_info(const char *date_str, const char *time_str);
void ui_hide_punch_display(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
