// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

lv_obj_t *ui_AdminLogin_Keyboard_AdminLogin_Keyboard_PasswordKeyboard;
lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_OkLabel;
lv_obj_t *ui_AdminLogin_Button_AdminLogin_Button_OkButton;
lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_CancelLabel;
lv_obj_t *ui_AdminLogin_Button_AdminLogin_Button_CancelButton;
lv_obj_t *ui_AdminLogin_Container_AdminLogin_Container_CancelOk;
lv_obj_t *ui_AdminLogin_Textarea_AdminLogin_Textarea_PasswordInput;
lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_PasswordLabel;
lv_obj_t *ui_AdminLogin_Container_AdminLogin_Container_PasswordContainer;
lv_obj_t *ui_AdminLogin_Container_CredentialContainer;
lv_obj_t *ui_Screen_AdminLogin;
lv_obj_t *ui_screen_adminlogin = NULL;lv_obj_t *ui_adminlogin_container_credentialcontainer = NULL;lv_obj_t *ui_adminlogin_container_passwordcontainer = NULL;lv_obj_t *ui_adminlogin_label_passwordlabel = NULL;lv_obj_t *ui_adminlogin_textarea_passwordinput = NULL;lv_obj_t *ui_adminlogin_container_cancelok = NULL;lv_obj_t *ui_adminlogin_button_cancelbutton = NULL;lv_obj_t *ui_adminlogin_label_cancellabel = NULL;lv_obj_t *ui_adminlogin_button_okbutton = NULL;lv_obj_t *ui_adminlogin_label_oklabel = NULL;lv_obj_t *ui_adminlogin_keyboard_passwordkeyboard = NULL;
// event funtions
void ui_event_adminlogin_textarea_passwordinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_adminlogin_keyboard_passwordkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      ui_event_textarea( e );
}
}

void ui_event_adminlogin_button_cancelbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_mainscreen_screen_init);
}
}

void ui_event_adminlogin_button_okbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setupconfigurations, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_setupconfigurations_screen_init);
}
}

void ui_event_adminlogin_keyboard_passwordkeyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_adminlogin_keyboard_passwordkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      ui_event_textarea( e );
}
if ( event_code == LV_EVENT_CANCEL) {
      _ui_keyboard_set_target(ui_adminlogin_keyboard_passwordkeyboard,  ui_adminlogin_textarea_passwordinput);
}
}

// build funtions

void ui_screen_adminlogin_screen_init(void)
{
ui_screen_adminlogin = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_adminlogin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_adminlogin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_adminlogin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_container_credentialcontainer = lv_obj_create(ui_screen_adminlogin);
lv_obj_remove_style_all(ui_adminlogin_container_credentialcontainer);
lv_obj_set_width( ui_adminlogin_container_credentialcontainer, 900);
lv_obj_set_height( ui_adminlogin_container_credentialcontainer, 500);
lv_obj_set_align( ui_adminlogin_container_credentialcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_adminlogin_container_credentialcontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_adminlogin_container_credentialcontainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_adminlogin_container_credentialcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adminlogin_container_passwordcontainer = lv_obj_create(ui_adminlogin_container_credentialcontainer);
lv_obj_remove_style_all(ui_adminlogin_container_passwordcontainer);
lv_obj_set_width( ui_adminlogin_container_passwordcontainer, 800);
lv_obj_set_height( ui_adminlogin_container_passwordcontainer, 125);
lv_obj_set_align( ui_adminlogin_container_passwordcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_adminlogin_container_passwordcontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_adminlogin_container_passwordcontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_adminlogin_container_passwordcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adminlogin_label_passwordlabel = lv_label_create(ui_adminlogin_container_passwordcontainer);
lv_obj_set_width( ui_adminlogin_label_passwordlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adminlogin_label_passwordlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adminlogin_label_passwordlabel, 0 );
lv_obj_set_y( ui_adminlogin_label_passwordlabel, -3 );
lv_obj_set_align( ui_adminlogin_label_passwordlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_adminlogin_label_passwordlabel,"Admin Access - Enter Password");
lv_obj_add_flag( ui_adminlogin_label_passwordlabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_adminlogin_label_passwordlabel, lv_color_hex(0x3399FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_adminlogin_label_passwordlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_adminlogin_label_passwordlabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_textarea_passwordinput = lv_textarea_create(ui_adminlogin_container_passwordcontainer);
lv_obj_set_width( ui_adminlogin_textarea_passwordinput, 530);
lv_obj_set_height( ui_adminlogin_textarea_passwordinput, 70);
lv_obj_set_x( ui_adminlogin_textarea_passwordinput, -104 );
lv_obj_set_y( ui_adminlogin_textarea_passwordinput, -94 );
lv_obj_set_align( ui_adminlogin_textarea_passwordinput, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_adminlogin_textarea_passwordinput,100);
lv_textarea_set_placeholder_text(ui_adminlogin_textarea_passwordinput,"Admin Password");
lv_textarea_set_password_mode(ui_adminlogin_textarea_passwordinput, true);
lv_obj_add_flag( ui_adminlogin_textarea_passwordinput, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_style_text_font(ui_adminlogin_textarea_passwordinput, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_adminlogin_textarea_passwordinput, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adminlogin_textarea_passwordinput, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_container_cancelok = lv_obj_create(ui_adminlogin_container_credentialcontainer);
lv_obj_remove_style_all(ui_adminlogin_container_cancelok);
lv_obj_set_width( ui_adminlogin_container_cancelok, 500);
lv_obj_set_height( ui_adminlogin_container_cancelok, 60);
lv_obj_set_x( ui_adminlogin_container_cancelok, 15 );
lv_obj_set_y( ui_adminlogin_container_cancelok, -331 );
lv_obj_set_align( ui_adminlogin_container_cancelok, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_adminlogin_container_cancelok,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_adminlogin_container_cancelok, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_adminlogin_container_cancelok, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adminlogin_button_cancelbutton = lv_button_create(ui_adminlogin_container_cancelok);
lv_obj_set_width( ui_adminlogin_button_cancelbutton, 100);
lv_obj_set_height( ui_adminlogin_button_cancelbutton, 50);
lv_obj_set_align( ui_adminlogin_button_cancelbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_adminlogin_button_cancelbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_adminlogin_button_cancelbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_adminlogin_button_cancelbutton, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adminlogin_button_cancelbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_label_cancellabel = lv_label_create(ui_adminlogin_button_cancelbutton);
lv_obj_set_width( ui_adminlogin_label_cancellabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adminlogin_label_cancellabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_adminlogin_label_cancellabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_adminlogin_label_cancellabel,"Cancel");
lv_obj_set_style_text_font(ui_adminlogin_label_cancellabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_button_okbutton = lv_button_create(ui_adminlogin_container_cancelok);
lv_obj_set_width( ui_adminlogin_button_okbutton, 100);
lv_obj_set_height( ui_adminlogin_button_okbutton, 50);
lv_obj_set_align( ui_adminlogin_button_okbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_adminlogin_button_okbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_adminlogin_button_okbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_adminlogin_button_okbutton, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adminlogin_button_okbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_adminlogin_button_okbutton, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_label_oklabel = lv_label_create(ui_adminlogin_button_okbutton);
lv_obj_set_width( ui_adminlogin_label_oklabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adminlogin_label_oklabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_adminlogin_label_oklabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_adminlogin_label_oklabel,"OK");
lv_obj_set_style_text_font(ui_adminlogin_label_oklabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adminlogin_keyboard_passwordkeyboard = lv_keyboard_create(ui_adminlogin_container_credentialcontainer);
lv_obj_set_width( ui_adminlogin_keyboard_passwordkeyboard, 900);
lv_obj_set_height( ui_adminlogin_keyboard_passwordkeyboard, 300);
lv_obj_set_x( ui_adminlogin_keyboard_passwordkeyboard, 18 );
lv_obj_set_y( ui_adminlogin_keyboard_passwordkeyboard, 20 );
lv_obj_set_align( ui_adminlogin_keyboard_passwordkeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_adminlogin_keyboard_passwordkeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_adminlogin_textarea_passwordinput, ui_event_adminlogin_textarea_passwordinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adminlogin_button_cancelbutton, ui_event_adminlogin_button_cancelbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adminlogin_button_okbutton, ui_event_adminlogin_button_okbutton, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_adminlogin_keyboard_passwordkeyboard,ui_adminlogin_textarea_passwordinput);
lv_obj_add_event_cb(ui_adminlogin_keyboard_passwordkeyboard, ui_event_adminlogin_keyboard_passwordkeyboard, LV_EVENT_ALL, NULL);
ui_Screen_AdminLogin = ui_screen_adminlogin;
ui_AdminLogin_Container_CredentialContainer = ui_adminlogin_container_credentialcontainer;
ui_AdminLogin_Container_AdminLogin_Container_PasswordContainer = ui_adminlogin_container_passwordcontainer;
ui_AdminLogin_Label_AdminLogin_Label_PasswordLabel = ui_adminlogin_label_passwordlabel;
ui_AdminLogin_Textarea_AdminLogin_Textarea_PasswordInput = ui_adminlogin_textarea_passwordinput;
ui_AdminLogin_Container_AdminLogin_Container_CancelOk = ui_adminlogin_container_cancelok;
ui_AdminLogin_Button_AdminLogin_Button_CancelButton = ui_adminlogin_button_cancelbutton;
ui_AdminLogin_Label_AdminLogin_Label_CancelLabel = ui_adminlogin_label_cancellabel;
ui_AdminLogin_Button_AdminLogin_Button_OkButton = ui_adminlogin_button_okbutton;
ui_AdminLogin_Label_AdminLogin_Label_OkLabel = ui_adminlogin_label_oklabel;
ui_AdminLogin_Keyboard_AdminLogin_Keyboard_PasswordKeyboard = ui_adminlogin_keyboard_passwordkeyboard;

}

void ui_screen_adminlogin_screen_destroy(void)
{
   if (ui_screen_adminlogin) lv_obj_del(ui_screen_adminlogin);

// NULL screen variables
ui_Screen_AdminLogin= NULL;
ui_screen_adminlogin= NULL;
ui_AdminLogin_Container_CredentialContainer= NULL;
ui_adminlogin_container_credentialcontainer= NULL;
ui_AdminLogin_Container_AdminLogin_Container_PasswordContainer= NULL;
ui_adminlogin_container_passwordcontainer= NULL;
ui_AdminLogin_Label_AdminLogin_Label_PasswordLabel= NULL;
ui_adminlogin_label_passwordlabel= NULL;
ui_AdminLogin_Textarea_AdminLogin_Textarea_PasswordInput= NULL;
ui_adminlogin_textarea_passwordinput= NULL;
ui_AdminLogin_Container_AdminLogin_Container_CancelOk= NULL;
ui_adminlogin_container_cancelok= NULL;
ui_AdminLogin_Button_AdminLogin_Button_CancelButton= NULL;
ui_adminlogin_button_cancelbutton= NULL;
ui_AdminLogin_Label_AdminLogin_Label_CancelLabel= NULL;
ui_adminlogin_label_cancellabel= NULL;
ui_AdminLogin_Button_AdminLogin_Button_OkButton= NULL;
ui_adminlogin_button_okbutton= NULL;
ui_AdminLogin_Label_AdminLogin_Label_OkLabel= NULL;
ui_adminlogin_label_oklabel= NULL;
ui_AdminLogin_Keyboard_AdminLogin_Keyboard_PasswordKeyboard= NULL;
ui_adminlogin_keyboard_passwordkeyboard= NULL;

}
