// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_WIREDSETUP_H
#define UI_SCREEN_WIREDSETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_wiredsetup
extern void ui_screen_wiredsetup_screen_init(void);
extern void ui_screen_wiredsetup_screen_destroy(void);
extern lv_obj_t *ui_screen_wiredsetup;
extern lv_obj_t *ui_wiredsetup_backgroundcontainer_backgroundcontainer5;
extern lv_obj_t *ui_wiredsetup_container_settingsenclosurecontainer;
extern lv_obj_t *ui_wiredsetup_container_infoheadercontainer;
extern lv_obj_t *ui_wiredsetup_label_lblwificonfig;
extern lv_obj_t *ui_wiredsetup_label_wifidisconnected;
extern lv_obj_t *ui_wiredsetup_container_hostnamecontainer;
extern lv_obj_t *ui_wiredsetup_label_hostnamelabel;
extern void ui_event_wiredsetup_textarea_hostnameinput( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_hostnameinput;
extern lv_obj_t *ui_wiredsetup_container_dhcpcontrolcontainer;
extern lv_obj_t *ui_wiredsetup_label_dhcpcontrollabel;
extern void ui_event_wiredsetup_switch_dhcpswitch( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_switch_dhcpswitch;
extern lv_obj_t *ui_wiredsetup_container_manualipsettingscontainer;
extern lv_obj_t *ui_wiredsetup_container_ipaddresscontainer;
extern lv_obj_t *ui_wiredsetup_label_ipaddresslabel;
extern void ui_event_wiredsetup_textarea_ipaddressinput( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_ipaddressinput;
extern lv_obj_t *ui_wiredsetup_container_gatewaycontainer;
extern lv_obj_t *ui_wiredsetup_label_gatewaylabel;
extern void ui_event_wiredsetup_textarea_gatewayinput( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_gatewayinput;
extern lv_obj_t *ui_wiredsetup_container_netmaskcontainer;
extern lv_obj_t *ui_wiredsetup_label_netmasklabel;
extern void ui_event_wiredsetup_textarea_netmaskinput( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_netmaskinput;
extern lv_obj_t *ui_wiredsetup_container_dnscontainer;
extern lv_obj_t *ui_wiredsetup_label_dnslabel;
extern void ui_event_wiredsetup_textarea_dnsinput( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_dnsinput;
extern lv_obj_t *ui_wiredsetup_container_dns2container;
extern lv_obj_t *ui_wiredsetup_label_dns2label;
extern void ui_event_wiredsetup_textarea_dns2input( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_textarea_dns2input;
extern void ui_event_wiredsetup_keyboard_networkkeyboard( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_keyboard_networkkeyboard;
extern lv_obj_t *ui_wiredsetup_container_cancelok;
extern void ui_event_wiredsetup_button_cancelbutton( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_button_cancelbutton;
extern lv_obj_t *ui_wiredsetup_label_cancellabel;
extern void ui_event_wiredsetup_button_okbutton( lv_event_t * e);
extern lv_obj_t *ui_wiredsetup_button_okbutton;
extern lv_obj_t *ui_wiredsetup_label_oklabel;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_WiredSetup;
extern lv_obj_t *ui_WiredSetup_BackGroundContainer_BackGroundContainer5;
extern lv_obj_t *ui_SettingsEnclosureContainer;
extern lv_obj_t *ui_WiredSetup_Container_InfoHeaderContainer;
extern lv_obj_t *ui_WiredSetup_Label_lblWifiConfig;
extern lv_obj_t *ui_WiredSetup_Label_WiFiDisconnected;
extern lv_obj_t *ui_WiredSetup_Container_HostnameContainer;
extern lv_obj_t *ui_WiredSetup_Label_HostnameLabel;
extern lv_obj_t *ui_WiredSetup_Textarea_HostnameInput;
extern lv_obj_t *ui_WiredSetup_Container_DhcpControlContainer;
extern lv_obj_t *ui_WiredSetup_Label_DhcpControlLabel;
extern lv_obj_t *ui_WiredSetup_Switch_DHCPSwitch;
extern lv_obj_t *ui_WiredSetup_Container_ManualIPSettingsContainer;
extern lv_obj_t *ui_WiredSetup_Container_ipAddressContainer;
extern lv_obj_t *ui_WiredSetup_Label_ipAddressLabel;
extern lv_obj_t *ui_WiredSetup_Textarea_ipAddressInput;
extern lv_obj_t *ui_WiredSetup_Container_GatewayContainer;
extern lv_obj_t *ui_WiredSetup_Label_GatewayLabel;
extern lv_obj_t *ui_WiredSetup_Textarea_GatewayInput;
extern lv_obj_t *ui_WiredSetup_Container_NetMaskContainer;
extern lv_obj_t *ui_WiredSetup_Label_NetMaskLabel;
extern lv_obj_t *ui_WiredSetup_Textarea_NetMaskInput;
extern lv_obj_t *ui_WiredSetup_Container_DNSContainer;
extern lv_obj_t *ui_WiredSetup_Label_DNSLabel;
extern lv_obj_t *ui_WiredSetup_Textarea_DNSInput;
extern lv_obj_t *ui_WiredSetup_Container_DNS2Container;
extern lv_obj_t *ui_WiredSetup_Label_DNS2Label;
extern lv_obj_t *ui_WiredSetup_Textarea_DNS2Input;
extern lv_obj_t *ui_WiredSetup_Keyboard_NetworkKeyboard;
extern lv_obj_t *ui_WiredSetup_Container_CancelOk;
extern lv_obj_t *ui_WiredSetup_Button_CancelButton;
extern lv_obj_t *ui_WiredSetup_Label_CancelLabel;
extern lv_obj_t *ui_WiredSetup_Button_OkButton;
extern lv_obj_t *ui_WiredSetup_Label_OkLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

