// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_ADMINLOGIN_H
#define UI_SCREEN_ADMINLOGIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_adminlogin
extern void ui_screen_adminlogin_screen_init(void);
extern void ui_screen_adminlogin_screen_destroy(void);
extern lv_obj_t *ui_screen_adminlogin;
extern lv_obj_t *ui_adminlogin_container_credentialcontainer;
extern lv_obj_t *ui_adminlogin_container_passwordcontainer;
extern lv_obj_t *ui_adminlogin_label_passwordlabel;
extern void ui_event_adminlogin_textarea_passwordinput( lv_event_t * e);
extern lv_obj_t *ui_adminlogin_textarea_passwordinput;
extern lv_obj_t *ui_adminlogin_container_cancelok;
extern void ui_event_adminlogin_button_cancelbutton( lv_event_t * e);
extern lv_obj_t *ui_adminlogin_button_cancelbutton;
extern lv_obj_t *ui_adminlogin_label_cancellabel;
extern void ui_event_adminlogin_button_okbutton( lv_event_t * e);
extern lv_obj_t *ui_adminlogin_button_okbutton;
extern lv_obj_t *ui_adminlogin_label_oklabel;
extern void ui_event_adminlogin_keyboard_passwordkeyboard( lv_event_t * e);
extern lv_obj_t *ui_adminlogin_keyboard_passwordkeyboard;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_AdminLogin;
extern lv_obj_t *ui_AdminLogin_Container_CredentialContainer;
extern lv_obj_t *ui_AdminLogin_Container_AdminLogin_Container_PasswordContainer;
extern lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_PasswordLabel;
extern lv_obj_t *ui_AdminLogin_Textarea_AdminLogin_Textarea_PasswordInput;
extern lv_obj_t *ui_AdminLogin_Container_AdminLogin_Container_CancelOk;
extern lv_obj_t *ui_AdminLogin_Button_AdminLogin_Button_CancelButton;
extern lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_CancelLabel;
extern lv_obj_t *ui_AdminLogin_Button_AdminLogin_Button_OkButton;
extern lv_obj_t *ui_AdminLogin_Label_AdminLogin_Label_OkLabel;
extern lv_obj_t *ui_AdminLogin_Keyboard_AdminLogin_Keyboard_PasswordKeyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

