// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_TIMEINFORMATION_H
#define UI_SCREEN_TIMEINFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_timeinformation
extern void ui_screen_timeinformation_screen_init(void);
extern void ui_screen_timeinformation_screen_destroy(void);
extern lv_obj_t *ui_screen_timeinformation;
extern lv_obj_t *ui_timeinformation_backgroundcontainer_backgroundcontainer6;
extern lv_obj_t *ui_timeinformation_container_syncbuttoncontainer;
extern lv_obj_t *ui_timeinformation_button_syncbutton;
extern lv_obj_t *ui_timeinformation_label_syncicon;
extern lv_obj_t *ui_timeinformation_label_syncnow;
extern lv_obj_t *ui_timeinformation_container_mastertimecontainer;
extern lv_obj_t *ui_timeinformation_container_timeinfocontainer;
extern lv_obj_t *ui_timeinformation_spinbox_timeinput;
extern lv_obj_t *ui_timeinformation_dropdown_ampm;
extern lv_obj_t *ui_timeinformation_label_timeinfolabel;
extern lv_obj_t *ui_timeinformation_container_mastertimezonecontainer;
extern lv_obj_t *ui_timeinformation_container_timezonecontainer;
extern lv_obj_t *ui_timeinformation_dropdown_timezone;
extern lv_obj_t *ui_timeinformation_label_timezonelabel;
extern lv_obj_t *ui_timeinformation_container_ntpcontainer;
extern lv_obj_t *ui_timeinformation_textarea_ntpinput;
extern lv_obj_t *ui_timeinformation_label_ntplabel;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_TimeInformation;
extern lv_obj_t *ui_BackGroundContainer6;
extern lv_obj_t *ui_TimeInformation_Container_SyncButtonContainer;
extern lv_obj_t *ui_TimeInformation_Button_syncButton;
extern lv_obj_t *ui_TimeInformation_Label_SyncIcon;
extern lv_obj_t *ui_TimeInformation_Label_SyncNow;
extern lv_obj_t *ui_TimeInformation_Container_MasterTimeContainer;
extern lv_obj_t *ui_TimeInformation_Container_TimeInfoContainer;
extern lv_obj_t *ui_TimeInformation_Dropdown_AMPM;
extern lv_obj_t *ui_TimeInformation_Label_TimeInfoLabel;
extern lv_obj_t *ui_TimeInformation_Container_TimeZoneContainer;
extern lv_obj_t *ui_TimeInformation_Dropdown_TimeZone;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

