// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef _SQUARELINE_TIMECLOCK_RAND_UI_H
#define _SQUARELINE_TIMECLOCK_RAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_screen_mainscreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui_startevents____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_Icons);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
