// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

void ui_link_keyboard_to_device_name(lv_event_t * e)
{
	// Your code here
}
