// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

lv_obj_t *ui_WiredSetup_Label_OkLabel;
lv_obj_t *ui_WiredSetup_Button_OkButton;
lv_obj_t *ui_WiredSetup_Label_CancelLabel;
lv_obj_t *ui_WiredSetup_Button_CancelButton;
lv_obj_t *ui_WiredSetup_Container_CancelOk;
lv_obj_t *ui_WiredSetup_Keyboard_NetworkKeyboard;
lv_obj_t *ui_WiredSetup_Textarea_DNS2Input;
lv_obj_t *ui_WiredSetup_Label_DNS2Label;
lv_obj_t *ui_WiredSetup_Container_DNS2Container;
lv_obj_t *ui_WiredSetup_Textarea_DNSInput;
lv_obj_t *ui_WiredSetup_Label_DNSLabel;
lv_obj_t *ui_WiredSetup_Container_DNSContainer;
lv_obj_t *ui_WiredSetup_Textarea_NetMaskInput;
lv_obj_t *ui_WiredSetup_Label_NetMaskLabel;
lv_obj_t *ui_WiredSetup_Container_NetMaskContainer;
lv_obj_t *ui_WiredSetup_Textarea_GatewayInput;
lv_obj_t *ui_WiredSetup_Label_GatewayLabel;
lv_obj_t *ui_WiredSetup_Container_GatewayContainer;
lv_obj_t *ui_WiredSetup_Textarea_ipAddressInput;
lv_obj_t *ui_WiredSetup_Label_ipAddressLabel;
lv_obj_t *ui_WiredSetup_Container_ipAddressContainer;
lv_obj_t *ui_WiredSetup_Container_ManualIPSettingsContainer;
lv_obj_t *ui_WiredSetup_Switch_DHCPSwitch;
lv_obj_t *ui_WiredSetup_Label_DhcpControlLabel;
lv_obj_t *ui_WiredSetup_Container_DhcpControlContainer;
lv_obj_t *ui_WiredSetup_Textarea_HostnameInput;
lv_obj_t *ui_WiredSetup_Label_HostnameLabel;
lv_obj_t *ui_WiredSetup_Container_HostnameContainer;
lv_obj_t *ui_WiredSetup_Label_WiFiDisconnected;
lv_obj_t *ui_WiredSetup_Label_lblWifiConfig;
lv_obj_t *ui_WiredSetup_Container_InfoHeaderContainer;
lv_obj_t *ui_SettingsEnclosureContainer;
lv_obj_t *ui_WiredSetup_BackGroundContainer_BackGroundContainer5;
lv_obj_t *ui_Screen_WiredSetup;
lv_obj_t *ui_screen_wiredsetup = NULL;lv_obj_t *ui_wiredsetup_backgroundcontainer_backgroundcontainer5 = NULL;lv_obj_t *ui_wiredsetup_container_settingsenclosurecontainer = NULL;lv_obj_t *ui_wiredsetup_container_infoheadercontainer = NULL;lv_obj_t *ui_wiredsetup_label_lblwificonfig = NULL;lv_obj_t *ui_wiredsetup_label_wifidisconnected = NULL;lv_obj_t *ui_wiredsetup_container_hostnamecontainer = NULL;lv_obj_t *ui_wiredsetup_label_hostnamelabel = NULL;lv_obj_t *ui_wiredsetup_textarea_hostnameinput = NULL;lv_obj_t *ui_wiredsetup_container_dhcpcontrolcontainer = NULL;lv_obj_t *ui_wiredsetup_label_dhcpcontrollabel = NULL;lv_obj_t *ui_wiredsetup_switch_dhcpswitch = NULL;lv_obj_t *ui_wiredsetup_container_manualipsettingscontainer = NULL;lv_obj_t *ui_wiredsetup_container_ipaddresscontainer = NULL;lv_obj_t *ui_wiredsetup_label_ipaddresslabel = NULL;lv_obj_t *ui_wiredsetup_textarea_ipaddressinput = NULL;lv_obj_t *ui_wiredsetup_container_gatewaycontainer = NULL;lv_obj_t *ui_wiredsetup_label_gatewaylabel = NULL;lv_obj_t *ui_wiredsetup_textarea_gatewayinput = NULL;lv_obj_t *ui_wiredsetup_container_netmaskcontainer = NULL;lv_obj_t *ui_wiredsetup_label_netmasklabel = NULL;lv_obj_t *ui_wiredsetup_textarea_netmaskinput = NULL;lv_obj_t *ui_wiredsetup_container_dnscontainer = NULL;lv_obj_t *ui_wiredsetup_label_dnslabel = NULL;lv_obj_t *ui_wiredsetup_textarea_dnsinput = NULL;lv_obj_t *ui_wiredsetup_container_dns2container = NULL;lv_obj_t *ui_wiredsetup_label_dns2label = NULL;lv_obj_t *ui_wiredsetup_textarea_dns2input = NULL;lv_obj_t *ui_wiredsetup_keyboard_networkkeyboard = NULL;lv_obj_t *ui_wiredsetup_container_cancelok = NULL;lv_obj_t *ui_wiredsetup_button_cancelbutton = NULL;lv_obj_t *ui_wiredsetup_label_cancellabel = NULL;lv_obj_t *ui_wiredsetup_button_okbutton = NULL;lv_obj_t *ui_wiredsetup_label_oklabel = NULL;
// event funtions
void ui_event_wiredsetup_textarea_hostnameinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_manualipsettingscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_hostnameinput);
      ui_event_textarea( e );
}
}

void ui_event_wiredsetup_switch_dhcpswitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_wiredsetup_container_manualipsettingscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_wiredsetup_container_manualipsettingscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_wiredsetup_textarea_ipaddressinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_ipaddressinput);
      ui_event_textarea( e );
      _ui_flag_modify( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_wiredsetup_textarea_gatewayinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_gatewayinput);
      ui_event_textarea( e );
      _ui_flag_modify( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_wiredsetup_textarea_netmaskinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_netmaskinput);
      ui_event_textarea( e );
      _ui_flag_modify( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_wiredsetup_textarea_dnsinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_dnsinput);
      ui_event_textarea( e );
      _ui_flag_modify( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_wiredsetup_textarea_dns2input( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_wiredsetup_keyboard_networkkeyboard,  ui_wiredsetup_textarea_dns2input);
      ui_event_textarea( e );
      _ui_flag_modify( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_wiredsetup_keyboard_networkkeyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CANCEL) {
      _ui_flag_modify( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_wiredsetup_button_cancelbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_mainscreen_screen_init);
}
}

void ui_event_wiredsetup_button_okbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setupconfigurations, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_setupconfigurations_screen_init);
}
}

// build funtions

void ui_screen_wiredsetup_screen_init(void)
{
ui_screen_wiredsetup = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_wiredsetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_backgroundcontainer_backgroundcontainer5 = ui_container_backgroundcontainer_create(ui_screen_wiredsetup);
lv_obj_set_x( ui_wiredsetup_backgroundcontainer_backgroundcontainer5, 0 );
lv_obj_set_y( ui_wiredsetup_backgroundcontainer_backgroundcontainer5, 0 );
lv_obj_set_flex_flow(ui_wiredsetup_backgroundcontainer_backgroundcontainer5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wiredsetup_backgroundcontainer_backgroundcontainer5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_wiredsetup_container_settingsenclosurecontainer = lv_obj_create(ui_wiredsetup_backgroundcontainer_backgroundcontainer5);
lv_obj_remove_style_all(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_set_width( ui_wiredsetup_container_settingsenclosurecontainer, 924);
lv_obj_set_height( ui_wiredsetup_container_settingsenclosurecontainer, 500);
lv_obj_set_align( ui_wiredsetup_container_settingsenclosurecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_settingsenclosurecontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wiredsetup_container_settingsenclosurecontainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_remove_flag( ui_wiredsetup_container_settingsenclosurecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scroll_dir(ui_wiredsetup_container_settingsenclosurecontainer, LV_DIR_HOR);
lv_obj_set_style_bg_color(ui_wiredsetup_container_settingsenclosurecontainer, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wiredsetup_container_settingsenclosurecontainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_infoheadercontainer = lv_obj_create(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_infoheadercontainer);
lv_obj_set_width( ui_wiredsetup_container_infoheadercontainer, 874);
lv_obj_set_height( ui_wiredsetup_container_infoheadercontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_infoheadercontainer, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_wiredsetup_container_infoheadercontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_infoheadercontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_wiredsetup_container_infoheadercontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_lblwificonfig = lv_label_create(ui_wiredsetup_container_infoheadercontainer);
lv_obj_set_width( ui_wiredsetup_label_lblwificonfig, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_lblwificonfig, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wiredsetup_label_lblwificonfig, 20 );
lv_obj_set_y( ui_wiredsetup_label_lblwificonfig, 23 );
lv_label_set_text(ui_wiredsetup_label_lblwificonfig,"Wired Configuration");
lv_obj_set_style_text_color(ui_wiredsetup_label_lblwificonfig, lv_color_hex(0x3399FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_lblwificonfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_wiredsetup_label_lblwificonfig, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_wiredsetup_label_lblwificonfig, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_wiredsetup_label_lblwificonfig, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_wiredsetup_label_lblwificonfig, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_label_wifidisconnected = lv_label_create(ui_wiredsetup_container_infoheadercontainer);
lv_obj_set_width( ui_wiredsetup_label_wifidisconnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_wifidisconnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wiredsetup_label_wifidisconnected, 682 );
lv_obj_set_y( ui_wiredsetup_label_wifidisconnected, 22 );
lv_label_set_text(ui_wiredsetup_label_wifidisconnected,"Disconnected");
lv_obj_set_style_pad_left(ui_wiredsetup_label_wifidisconnected, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_wiredsetup_label_wifidisconnected, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_wiredsetup_label_wifidisconnected, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_wiredsetup_label_wifidisconnected, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_hostnamecontainer = lv_obj_create(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_hostnamecontainer);
lv_obj_set_width( ui_wiredsetup_container_hostnamecontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_hostnamecontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_hostnamecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_hostnamecontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_hostnamecontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_hostnamecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_hostnamelabel = lv_label_create(ui_wiredsetup_container_hostnamecontainer);
lv_obj_set_width( ui_wiredsetup_label_hostnamelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_hostnamelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_hostnamelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_hostnamelabel,"Hostname:");
lv_obj_set_style_text_color(ui_wiredsetup_label_hostnamelabel, lv_color_hex(0x3399FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_hostnamelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_hostnamelabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_hostnameinput = lv_textarea_create(ui_wiredsetup_container_hostnamecontainer);
lv_obj_set_width( ui_wiredsetup_textarea_hostnameinput, 500);
lv_obj_set_height( ui_wiredsetup_textarea_hostnameinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_wiredsetup_textarea_hostnameinput, 0 );
lv_obj_set_y( ui_wiredsetup_textarea_hostnameinput, 2 );
lv_obj_set_align( ui_wiredsetup_textarea_hostnameinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_hostnameinput,"Hostname");
lv_textarea_set_one_line(ui_wiredsetup_textarea_hostnameinput,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_hostnameinput, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_dhcpcontrolcontainer = lv_obj_create(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_dhcpcontrolcontainer);
lv_obj_set_width( ui_wiredsetup_container_dhcpcontrolcontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_dhcpcontrolcontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_dhcpcontrolcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_dhcpcontrolcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_dhcpcontrolcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_dhcpcontrolcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_dhcpcontrollabel = lv_label_create(ui_wiredsetup_container_dhcpcontrolcontainer);
lv_obj_set_width( ui_wiredsetup_label_dhcpcontrollabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_dhcpcontrollabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_dhcpcontrollabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_dhcpcontrollabel,"DHCP (Auto IP):");
lv_obj_set_style_text_color(ui_wiredsetup_label_dhcpcontrollabel, lv_color_hex(0x3399FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_dhcpcontrollabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_dhcpcontrollabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_switch_dhcpswitch = lv_switch_create(ui_wiredsetup_container_dhcpcontrolcontainer);
lv_obj_set_width( ui_wiredsetup_switch_dhcpswitch, 50);
lv_obj_set_height( ui_wiredsetup_switch_dhcpswitch, 25);
lv_obj_set_align( ui_wiredsetup_switch_dhcpswitch, LV_ALIGN_CENTER );
lv_obj_add_state( ui_wiredsetup_switch_dhcpswitch, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_wiredsetup_switch_dhcpswitch, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_wiredsetup_container_manualipsettingscontainer = lv_obj_create(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_set_width( ui_wiredsetup_container_manualipsettingscontainer, 849);
lv_obj_set_height( ui_wiredsetup_container_manualipsettingscontainer, 249);
lv_obj_set_x( ui_wiredsetup_container_manualipsettingscontainer, 0 );
lv_obj_set_y( ui_wiredsetup_container_manualipsettingscontainer, 152 );
lv_obj_set_align( ui_wiredsetup_container_manualipsettingscontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_manualipsettingscontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wiredsetup_container_manualipsettingscontainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_wiredsetup_container_manualipsettingscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_container_ipaddresscontainer = lv_obj_create(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_ipaddresscontainer);
lv_obj_set_width( ui_wiredsetup_container_ipaddresscontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_ipaddresscontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_ipaddresscontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_ipaddresscontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_ipaddresscontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_ipaddresscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_ipaddresslabel = lv_label_create(ui_wiredsetup_container_ipaddresscontainer);
lv_obj_set_width( ui_wiredsetup_label_ipaddresslabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_ipaddresslabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_ipaddresslabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_ipaddresslabel,"IP:");
lv_obj_set_style_text_color(ui_wiredsetup_label_ipaddresslabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_ipaddresslabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_ipaddresslabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_ipaddressinput = lv_textarea_create(ui_wiredsetup_container_ipaddresscontainer);
lv_obj_set_width( ui_wiredsetup_textarea_ipaddressinput, 500);
lv_obj_set_height( ui_wiredsetup_textarea_ipaddressinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_wiredsetup_textarea_ipaddressinput, LV_ALIGN_CENTER );
lv_textarea_set_accepted_chars(ui_wiredsetup_textarea_ipaddressinput, "0123456789.");
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_ipaddressinput,"IP: 192.168.1.100");
lv_textarea_set_one_line(ui_wiredsetup_textarea_ipaddressinput,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_ipaddressinput, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_gatewaycontainer = lv_obj_create(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_gatewaycontainer);
lv_obj_set_width( ui_wiredsetup_container_gatewaycontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_gatewaycontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_gatewaycontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_gatewaycontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_gatewaycontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_gatewaycontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_gatewaylabel = lv_label_create(ui_wiredsetup_container_gatewaycontainer);
lv_obj_set_width( ui_wiredsetup_label_gatewaylabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_gatewaylabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_gatewaylabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_gatewaylabel,"Gateway:");
lv_obj_set_style_text_color(ui_wiredsetup_label_gatewaylabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_gatewaylabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_gatewaylabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_gatewayinput = lv_textarea_create(ui_wiredsetup_container_gatewaycontainer);
lv_obj_set_width( ui_wiredsetup_textarea_gatewayinput, 500);
lv_obj_set_height( ui_wiredsetup_textarea_gatewayinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_wiredsetup_textarea_gatewayinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_gatewayinput,"Gateway: 192.168.1.1");
lv_textarea_set_one_line(ui_wiredsetup_textarea_gatewayinput,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_gatewayinput, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_netmaskcontainer = lv_obj_create(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_netmaskcontainer);
lv_obj_set_width( ui_wiredsetup_container_netmaskcontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_netmaskcontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_netmaskcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_netmaskcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_netmaskcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_netmaskcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_netmasklabel = lv_label_create(ui_wiredsetup_container_netmaskcontainer);
lv_obj_set_width( ui_wiredsetup_label_netmasklabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_netmasklabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_netmasklabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_netmasklabel,"Netmask:");
lv_obj_set_style_text_color(ui_wiredsetup_label_netmasklabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_netmasklabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_netmasklabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_netmaskinput = lv_textarea_create(ui_wiredsetup_container_netmaskcontainer);
lv_obj_set_width( ui_wiredsetup_textarea_netmaskinput, 500);
lv_obj_set_height( ui_wiredsetup_textarea_netmaskinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_wiredsetup_textarea_netmaskinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_netmaskinput,"NetMask: 255.255.255.0");
lv_textarea_set_one_line(ui_wiredsetup_textarea_netmaskinput,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_netmaskinput, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_dnscontainer = lv_obj_create(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_dnscontainer);
lv_obj_set_width( ui_wiredsetup_container_dnscontainer, 850);
lv_obj_set_height( ui_wiredsetup_container_dnscontainer, 50);
lv_obj_set_align( ui_wiredsetup_container_dnscontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_dnscontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_dnscontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_dnscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_dnslabel = lv_label_create(ui_wiredsetup_container_dnscontainer);
lv_obj_set_width( ui_wiredsetup_label_dnslabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_dnslabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_dnslabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_dnslabel,"DNS:");
lv_obj_set_style_text_color(ui_wiredsetup_label_dnslabel, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_dnslabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_dnslabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_dnsinput = lv_textarea_create(ui_wiredsetup_container_dnscontainer);
lv_obj_set_width( ui_wiredsetup_textarea_dnsinput, 500);
lv_obj_set_height( ui_wiredsetup_textarea_dnsinput, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_wiredsetup_textarea_dnsinput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_dnsinput,"DNS1: 8.8.8.8");
lv_textarea_set_one_line(ui_wiredsetup_textarea_dnsinput,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_dnsinput, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_container_dns2container = lv_obj_create(ui_wiredsetup_container_manualipsettingscontainer);
lv_obj_remove_style_all(ui_wiredsetup_container_dns2container);
lv_obj_set_width( ui_wiredsetup_container_dns2container, 850);
lv_obj_set_height( ui_wiredsetup_container_dns2container, 50);
lv_obj_set_align( ui_wiredsetup_container_dns2container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wiredsetup_container_dns2container,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_dns2container, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_dns2container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wiredsetup_label_dns2label = lv_label_create(ui_wiredsetup_container_dns2container);
lv_obj_set_width( ui_wiredsetup_label_dns2label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_dns2label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_dns2label, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_dns2label,"DNS2:");
lv_obj_set_style_text_color(ui_wiredsetup_label_dns2label, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wiredsetup_label_dns2label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_label_dns2label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_textarea_dns2input = lv_textarea_create(ui_wiredsetup_container_dns2container);
lv_obj_set_width( ui_wiredsetup_textarea_dns2input, 500);
lv_obj_set_height( ui_wiredsetup_textarea_dns2input, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_wiredsetup_textarea_dns2input, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wiredsetup_textarea_dns2input,"DNS2: 8.8.8.8");
lv_textarea_set_one_line(ui_wiredsetup_textarea_dns2input,true);
lv_obj_set_style_text_font(ui_wiredsetup_textarea_dns2input, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_keyboard_networkkeyboard = lv_keyboard_create(ui_wiredsetup_container_settingsenclosurecontainer);
lv_obj_set_width( ui_wiredsetup_keyboard_networkkeyboard, 831);
lv_obj_set_height( ui_wiredsetup_keyboard_networkkeyboard, 281);
lv_obj_set_x( ui_wiredsetup_keyboard_networkkeyboard, 2 );
lv_obj_set_y( ui_wiredsetup_keyboard_networkkeyboard, 95 );
lv_obj_set_align( ui_wiredsetup_keyboard_networkkeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wiredsetup_keyboard_networkkeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_move_to_index(ui_wiredsetup_container_settingsenclosurecontainer,0);
ui_wiredsetup_container_cancelok = lv_obj_create(ui_wiredsetup_backgroundcontainer_backgroundcontainer5);
lv_obj_remove_style_all(ui_wiredsetup_container_cancelok);
lv_obj_set_width( ui_wiredsetup_container_cancelok, 924);
lv_obj_set_height( ui_wiredsetup_container_cancelok, 60);
lv_obj_set_x( ui_wiredsetup_container_cancelok, 15 );
lv_obj_set_y( ui_wiredsetup_container_cancelok, -331 );
lv_obj_set_align( ui_wiredsetup_container_cancelok, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_wiredsetup_container_cancelok,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wiredsetup_container_cancelok, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wiredsetup_container_cancelok, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wiredsetup_container_cancelok, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wiredsetup_container_cancelok, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_button_cancelbutton = lv_button_create(ui_wiredsetup_container_cancelok);
lv_obj_set_width( ui_wiredsetup_button_cancelbutton, 100);
lv_obj_set_height( ui_wiredsetup_button_cancelbutton, 50);
lv_obj_set_align( ui_wiredsetup_button_cancelbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wiredsetup_button_cancelbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wiredsetup_button_cancelbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wiredsetup_button_cancelbutton, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wiredsetup_button_cancelbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_label_cancellabel = lv_label_create(ui_wiredsetup_button_cancelbutton);
lv_obj_set_width( ui_wiredsetup_label_cancellabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_cancellabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_cancellabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_cancellabel,"Cancel");
lv_obj_set_style_text_font(ui_wiredsetup_label_cancellabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_button_okbutton = lv_button_create(ui_wiredsetup_container_cancelok);
lv_obj_set_width( ui_wiredsetup_button_okbutton, 100);
lv_obj_set_height( ui_wiredsetup_button_okbutton, 50);
lv_obj_set_align( ui_wiredsetup_button_okbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wiredsetup_button_okbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wiredsetup_button_okbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wiredsetup_button_okbutton, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wiredsetup_button_okbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wiredsetup_button_okbutton, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wiredsetup_label_oklabel = lv_label_create(ui_wiredsetup_button_okbutton);
lv_obj_set_width( ui_wiredsetup_label_oklabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wiredsetup_label_oklabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wiredsetup_label_oklabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wiredsetup_label_oklabel,"OK");
lv_obj_set_style_text_font(ui_wiredsetup_label_oklabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_move_to_index(ui_wiredsetup_container_cancelok,1);
lv_obj_add_event_cb(ui_wiredsetup_textarea_hostnameinput, ui_event_wiredsetup_textarea_hostnameinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_switch_dhcpswitch, ui_event_wiredsetup_switch_dhcpswitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_textarea_ipaddressinput, ui_event_wiredsetup_textarea_ipaddressinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_textarea_gatewayinput, ui_event_wiredsetup_textarea_gatewayinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_textarea_netmaskinput, ui_event_wiredsetup_textarea_netmaskinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_textarea_dnsinput, ui_event_wiredsetup_textarea_dnsinput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_textarea_dns2input, ui_event_wiredsetup_textarea_dns2input, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_keyboard_networkkeyboard, ui_event_wiredsetup_keyboard_networkkeyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_button_cancelbutton, ui_event_wiredsetup_button_cancelbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiredsetup_button_okbutton, ui_event_wiredsetup_button_okbutton, LV_EVENT_ALL, NULL);
ui_Screen_WiredSetup = ui_screen_wiredsetup;
ui_WiredSetup_BackGroundContainer_BackGroundContainer5 = ui_wiredsetup_backgroundcontainer_backgroundcontainer5;
ui_SettingsEnclosureContainer = ui_wiredsetup_container_settingsenclosurecontainer;
ui_WiredSetup_Container_InfoHeaderContainer = ui_wiredsetup_container_infoheadercontainer;
ui_WiredSetup_Label_lblWifiConfig = ui_wiredsetup_label_lblwificonfig;
ui_WiredSetup_Label_WiFiDisconnected = ui_wiredsetup_label_wifidisconnected;
ui_WiredSetup_Container_HostnameContainer = ui_wiredsetup_container_hostnamecontainer;
ui_WiredSetup_Label_HostnameLabel = ui_wiredsetup_label_hostnamelabel;
ui_WiredSetup_Textarea_HostnameInput = ui_wiredsetup_textarea_hostnameinput;
ui_WiredSetup_Container_DhcpControlContainer = ui_wiredsetup_container_dhcpcontrolcontainer;
ui_WiredSetup_Label_DhcpControlLabel = ui_wiredsetup_label_dhcpcontrollabel;
ui_WiredSetup_Switch_DHCPSwitch = ui_wiredsetup_switch_dhcpswitch;
ui_WiredSetup_Container_ManualIPSettingsContainer = ui_wiredsetup_container_manualipsettingscontainer;
ui_WiredSetup_Container_ipAddressContainer = ui_wiredsetup_container_ipaddresscontainer;
ui_WiredSetup_Label_ipAddressLabel = ui_wiredsetup_label_ipaddresslabel;
ui_WiredSetup_Textarea_ipAddressInput = ui_wiredsetup_textarea_ipaddressinput;
ui_WiredSetup_Container_GatewayContainer = ui_wiredsetup_container_gatewaycontainer;
ui_WiredSetup_Label_GatewayLabel = ui_wiredsetup_label_gatewaylabel;
ui_WiredSetup_Textarea_GatewayInput = ui_wiredsetup_textarea_gatewayinput;
ui_WiredSetup_Container_NetMaskContainer = ui_wiredsetup_container_netmaskcontainer;
ui_WiredSetup_Label_NetMaskLabel = ui_wiredsetup_label_netmasklabel;
ui_WiredSetup_Textarea_NetMaskInput = ui_wiredsetup_textarea_netmaskinput;
ui_WiredSetup_Container_DNSContainer = ui_wiredsetup_container_dnscontainer;
ui_WiredSetup_Label_DNSLabel = ui_wiredsetup_label_dnslabel;
ui_WiredSetup_Textarea_DNSInput = ui_wiredsetup_textarea_dnsinput;
ui_WiredSetup_Container_DNS2Container = ui_wiredsetup_container_dns2container;
ui_WiredSetup_Label_DNS2Label = ui_wiredsetup_label_dns2label;
ui_WiredSetup_Textarea_DNS2Input = ui_wiredsetup_textarea_dns2input;
ui_WiredSetup_Keyboard_NetworkKeyboard = ui_wiredsetup_keyboard_networkkeyboard;
ui_WiredSetup_Container_CancelOk = ui_wiredsetup_container_cancelok;
ui_WiredSetup_Button_CancelButton = ui_wiredsetup_button_cancelbutton;
ui_WiredSetup_Label_CancelLabel = ui_wiredsetup_label_cancellabel;
ui_WiredSetup_Button_OkButton = ui_wiredsetup_button_okbutton;
ui_WiredSetup_Label_OkLabel = ui_wiredsetup_label_oklabel;

}

void ui_screen_wiredsetup_screen_destroy(void)
{
   if (ui_screen_wiredsetup) lv_obj_del(ui_screen_wiredsetup);

// NULL screen variables
ui_Screen_WiredSetup= NULL;
ui_screen_wiredsetup= NULL;
ui_WiredSetup_BackGroundContainer_BackGroundContainer5= NULL;
ui_wiredsetup_backgroundcontainer_backgroundcontainer5= NULL;
ui_SettingsEnclosureContainer= NULL;
ui_wiredsetup_container_settingsenclosurecontainer= NULL;
ui_WiredSetup_Container_InfoHeaderContainer= NULL;
ui_wiredsetup_container_infoheadercontainer= NULL;
ui_WiredSetup_Label_lblWifiConfig= NULL;
ui_wiredsetup_label_lblwificonfig= NULL;
ui_WiredSetup_Label_WiFiDisconnected= NULL;
ui_wiredsetup_label_wifidisconnected= NULL;
ui_WiredSetup_Container_HostnameContainer= NULL;
ui_wiredsetup_container_hostnamecontainer= NULL;
ui_WiredSetup_Label_HostnameLabel= NULL;
ui_wiredsetup_label_hostnamelabel= NULL;
ui_WiredSetup_Textarea_HostnameInput= NULL;
ui_wiredsetup_textarea_hostnameinput= NULL;
ui_WiredSetup_Container_DhcpControlContainer= NULL;
ui_wiredsetup_container_dhcpcontrolcontainer= NULL;
ui_WiredSetup_Label_DhcpControlLabel= NULL;
ui_wiredsetup_label_dhcpcontrollabel= NULL;
ui_WiredSetup_Switch_DHCPSwitch= NULL;
ui_wiredsetup_switch_dhcpswitch= NULL;
ui_WiredSetup_Container_ManualIPSettingsContainer= NULL;
ui_wiredsetup_container_manualipsettingscontainer= NULL;
ui_WiredSetup_Container_ipAddressContainer= NULL;
ui_wiredsetup_container_ipaddresscontainer= NULL;
ui_WiredSetup_Label_ipAddressLabel= NULL;
ui_wiredsetup_label_ipaddresslabel= NULL;
ui_WiredSetup_Textarea_ipAddressInput= NULL;
ui_wiredsetup_textarea_ipaddressinput= NULL;
ui_WiredSetup_Container_GatewayContainer= NULL;
ui_wiredsetup_container_gatewaycontainer= NULL;
ui_WiredSetup_Label_GatewayLabel= NULL;
ui_wiredsetup_label_gatewaylabel= NULL;
ui_WiredSetup_Textarea_GatewayInput= NULL;
ui_wiredsetup_textarea_gatewayinput= NULL;
ui_WiredSetup_Container_NetMaskContainer= NULL;
ui_wiredsetup_container_netmaskcontainer= NULL;
ui_WiredSetup_Label_NetMaskLabel= NULL;
ui_wiredsetup_label_netmasklabel= NULL;
ui_WiredSetup_Textarea_NetMaskInput= NULL;
ui_wiredsetup_textarea_netmaskinput= NULL;
ui_WiredSetup_Container_DNSContainer= NULL;
ui_wiredsetup_container_dnscontainer= NULL;
ui_WiredSetup_Label_DNSLabel= NULL;
ui_wiredsetup_label_dnslabel= NULL;
ui_WiredSetup_Textarea_DNSInput= NULL;
ui_wiredsetup_textarea_dnsinput= NULL;
ui_WiredSetup_Container_DNS2Container= NULL;
ui_wiredsetup_container_dns2container= NULL;
ui_WiredSetup_Label_DNS2Label= NULL;
ui_wiredsetup_label_dns2label= NULL;
ui_WiredSetup_Textarea_DNS2Input= NULL;
ui_wiredsetup_textarea_dns2input= NULL;
ui_WiredSetup_Keyboard_NetworkKeyboard= NULL;
ui_wiredsetup_keyboard_networkkeyboard= NULL;
ui_WiredSetup_Container_CancelOk= NULL;
ui_wiredsetup_container_cancelok= NULL;
ui_WiredSetup_Button_CancelButton= NULL;
ui_wiredsetup_button_cancelbutton= NULL;
ui_WiredSetup_Label_CancelLabel= NULL;
ui_wiredsetup_label_cancellabel= NULL;
ui_WiredSetup_Button_OkButton= NULL;
ui_wiredsetup_button_okbutton= NULL;
ui_WiredSetup_Label_OkLabel= NULL;
ui_wiredsetup_label_oklabel= NULL;

}
