// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

lv_obj_t *ui_TimeInformation_Dropdown_TimeZone;
lv_obj_t *ui_TimeInformation_Container_TimeZoneContainer;
lv_obj_t *ui_TimeInformation_Label_TimeInfoLabel;
lv_obj_t *ui_TimeInformation_Dropdown_AMPM;
lv_obj_t *ui_TimeInformation_Container_TimeInfoContainer;
lv_obj_t *ui_TimeInformation_Container_MasterTimeContainer;
lv_obj_t *ui_TimeInformation_Label_SyncNow;
lv_obj_t *ui_TimeInformation_Label_SyncIcon;
lv_obj_t *ui_TimeInformation_Button_syncButton;
lv_obj_t *ui_TimeInformation_Container_SyncButtonContainer;
lv_obj_t *ui_BackGroundContainer6;
lv_obj_t *ui_Screen_TimeInformation;
lv_obj_t *ui_screen_timeinformation = NULL;lv_obj_t *ui_timeinformation_backgroundcontainer_backgroundcontainer6 = NULL;lv_obj_t *ui_timeinformation_container_syncbuttoncontainer = NULL;lv_obj_t *ui_timeinformation_button_syncbutton = NULL;lv_obj_t *ui_timeinformation_label_syncicon = NULL;lv_obj_t *ui_timeinformation_label_syncnow = NULL;lv_obj_t *ui_timeinformation_container_mastertimecontainer = NULL;lv_obj_t *ui_timeinformation_container_timeinfocontainer = NULL;lv_obj_t *ui_timeinformation_spinbox_timeinput = NULL;lv_obj_t *ui_timeinformation_dropdown_ampm = NULL;lv_obj_t *ui_timeinformation_label_timeinfolabel = NULL;lv_obj_t *ui_timeinformation_container_mastertimezonecontainer = NULL;lv_obj_t *ui_timeinformation_container_timezonecontainer = NULL;lv_obj_t *ui_timeinformation_dropdown_timezone = NULL;lv_obj_t *ui_timeinformation_label_timezonelabel = NULL;lv_obj_t *ui_timeinformation_container_ntpcontainer = NULL;lv_obj_t *ui_timeinformation_textarea_ntpinput = NULL;lv_obj_t *ui_timeinformation_label_ntplabel = NULL;
// event funtions

// build funtions

void ui_screen_timeinformation_screen_init(void)
{
ui_screen_timeinformation = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_timeinformation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_screen_timeinformation, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_outline_color(ui_screen_timeinformation, lv_color_hex(0xF50707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_screen_timeinformation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeinformation_backgroundcontainer_backgroundcontainer6 = ui_container_backgroundcontainer_create(ui_screen_timeinformation);
lv_obj_set_x( ui_timeinformation_backgroundcontainer_backgroundcontainer6, 0 );
lv_obj_set_y( ui_timeinformation_backgroundcontainer_backgroundcontainer6, 0 );
lv_obj_set_style_layout(ui_timeinformation_backgroundcontainer_backgroundcontainer6, 0, 0);

ui_timeinformation_container_syncbuttoncontainer = lv_obj_create(ui_screen_timeinformation);
lv_obj_remove_style_all(ui_timeinformation_container_syncbuttoncontainer);
lv_obj_set_width( ui_timeinformation_container_syncbuttoncontainer, 264);
lv_obj_set_height( ui_timeinformation_container_syncbuttoncontainer, 72);
lv_obj_set_x( ui_timeinformation_container_syncbuttoncontainer, 380 );
lv_obj_set_y( ui_timeinformation_container_syncbuttoncontainer, 52 );
lv_obj_set_flex_flow(ui_timeinformation_container_syncbuttoncontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timeinformation_container_syncbuttoncontainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_timeinformation_container_syncbuttoncontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_button_syncbutton = lv_button_create(ui_timeinformation_container_syncbuttoncontainer);
lv_obj_set_align( ui_timeinformation_button_syncbutton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_button_syncbutton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_timeinformation_button_syncbutton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_timeinformation_button_syncbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_timeinformation_button_syncbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_label_syncicon = lv_label_create(ui_timeinformation_button_syncbutton);
lv_obj_set_width( ui_timeinformation_label_syncicon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeinformation_label_syncicon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_timeinformation_label_syncicon, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeinformation_label_syncicon,"");
lv_obj_set_style_text_font(ui_timeinformation_label_syncicon, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeinformation_label_syncnow = lv_label_create(ui_timeinformation_button_syncbutton);
lv_obj_set_width( ui_timeinformation_label_syncnow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeinformation_label_syncnow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeinformation_label_syncnow, 83 );
lv_obj_set_y( ui_timeinformation_label_syncnow, 5 );
lv_obj_set_align( ui_timeinformation_label_syncnow, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeinformation_label_syncnow,"Sync Now");

ui_timeinformation_container_mastertimecontainer = lv_obj_create(ui_screen_timeinformation);
lv_obj_remove_style_all(ui_timeinformation_container_mastertimecontainer);
lv_obj_set_width( ui_timeinformation_container_mastertimecontainer, 274);
lv_obj_set_height( ui_timeinformation_container_mastertimecontainer, 75);
lv_obj_set_x( ui_timeinformation_container_mastertimecontainer, 2 );
lv_obj_set_y( ui_timeinformation_container_mastertimecontainer, -87 );
lv_obj_set_align( ui_timeinformation_container_mastertimecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_container_mastertimecontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timeinformation_container_mastertimecontainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_timeinformation_container_mastertimecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_container_timeinfocontainer = lv_obj_create(ui_timeinformation_container_mastertimecontainer);
lv_obj_remove_style_all(ui_timeinformation_container_timeinfocontainer);
lv_obj_set_width( ui_timeinformation_container_timeinfocontainer, 261);
lv_obj_set_height( ui_timeinformation_container_timeinfocontainer, 64);
lv_obj_set_x( ui_timeinformation_container_timeinfocontainer, 2 );
lv_obj_set_y( ui_timeinformation_container_timeinfocontainer, -8 );
lv_obj_set_align( ui_timeinformation_container_timeinfocontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_container_timeinfocontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_timeinformation_container_timeinfocontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_remove_flag( ui_timeinformation_container_timeinfocontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_spinbox_timeinput = lv_spinbox_create(ui_timeinformation_container_timeinfocontainer);
lv_obj_set_width( ui_timeinformation_spinbox_timeinput, 165);
lv_obj_set_height( ui_timeinformation_spinbox_timeinput, 42);
lv_obj_set_x( ui_timeinformation_spinbox_timeinput, 83 );
lv_obj_set_y( ui_timeinformation_spinbox_timeinput, -14 );
lv_obj_set_align( ui_timeinformation_spinbox_timeinput, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_timeinformation_spinbox_timeinput, 4, 2);
lv_spinbox_set_range( ui_timeinformation_spinbox_timeinput, 0,9999 );
lv_spinbox_set_cursor_pos(ui_timeinformation_spinbox_timeinput, 1 - 1);

ui_timeinformation_dropdown_ampm = lv_dropdown_create(ui_timeinformation_container_timeinfocontainer);
lv_dropdown_set_options( ui_timeinformation_dropdown_ampm, "AM\nPM" );
lv_obj_set_width( ui_timeinformation_dropdown_ampm, 87);
lv_obj_set_height( ui_timeinformation_dropdown_ampm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeinformation_dropdown_ampm, -6804 );
lv_obj_set_y( ui_timeinformation_dropdown_ampm, 481 );
lv_obj_set_align( ui_timeinformation_dropdown_ampm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_timeinformation_dropdown_ampm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_timeinformation_label_timeinfolabel = lv_label_create(ui_timeinformation_container_mastertimecontainer);
lv_obj_set_width( ui_timeinformation_label_timeinfolabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeinformation_label_timeinfolabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_timeinformation_label_timeinfolabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeinformation_label_timeinfolabel,"Time Input");
lv_obj_set_style_text_color(ui_timeinformation_label_timeinfolabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeinformation_label_timeinfolabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeinformation_container_mastertimezonecontainer = lv_obj_create(ui_screen_timeinformation);
lv_obj_remove_style_all(ui_timeinformation_container_mastertimezonecontainer);
lv_obj_set_width( ui_timeinformation_container_mastertimezonecontainer, 274);
lv_obj_set_height( ui_timeinformation_container_mastertimezonecontainer, 75);
lv_obj_set_x( ui_timeinformation_container_mastertimezonecontainer, 0 );
lv_obj_set_y( ui_timeinformation_container_mastertimezonecontainer, -6 );
lv_obj_set_align( ui_timeinformation_container_mastertimezonecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_container_mastertimezonecontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timeinformation_container_mastertimezonecontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_timeinformation_container_mastertimezonecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_container_timezonecontainer = lv_obj_create(ui_timeinformation_container_mastertimezonecontainer);
lv_obj_remove_style_all(ui_timeinformation_container_timezonecontainer);
lv_obj_set_width( ui_timeinformation_container_timezonecontainer, 269);
lv_obj_set_height( ui_timeinformation_container_timezonecontainer, 63);
lv_obj_set_x( ui_timeinformation_container_timezonecontainer, 2 );
lv_obj_set_y( ui_timeinformation_container_timezonecontainer, -81 );
lv_obj_set_align( ui_timeinformation_container_timezonecontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_container_timezonecontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timeinformation_container_timezonecontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_timeinformation_container_timezonecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_dropdown_timezone = lv_dropdown_create(ui_timeinformation_container_timezonecontainer);
lv_dropdown_set_options( ui_timeinformation_dropdown_timezone, "Alaska Standard Time\nAtlantic Standard Time\nCentral Standard Time\nChamorro Standard Time\nEastern Standard Time\nHawaii–Aleutian Standard Time\nMountain Standard Time\nPacific Standard Time\nSamoa Standard Time" );
lv_obj_set_width( ui_timeinformation_dropdown_timezone, 267);
lv_obj_set_height( ui_timeinformation_dropdown_timezone, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeinformation_dropdown_timezone, 17 );
lv_obj_set_y( ui_timeinformation_dropdown_timezone, 2 );
lv_obj_set_align( ui_timeinformation_dropdown_timezone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_timeinformation_dropdown_timezone, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_timeinformation_label_timezonelabel = lv_label_create(ui_timeinformation_container_mastertimezonecontainer);
lv_obj_set_width( ui_timeinformation_label_timezonelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeinformation_label_timezonelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeinformation_label_timezonelabel, 93 );
lv_obj_set_y( ui_timeinformation_label_timezonelabel, -47 );
lv_obj_set_align( ui_timeinformation_label_timezonelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeinformation_label_timezonelabel,"TimeZone");
lv_obj_set_style_text_color(ui_timeinformation_label_timezonelabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeinformation_label_timezonelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeinformation_container_ntpcontainer = lv_obj_create(ui_screen_timeinformation);
lv_obj_remove_style_all(ui_timeinformation_container_ntpcontainer);
lv_obj_set_width( ui_timeinformation_container_ntpcontainer, 274);
lv_obj_set_height( ui_timeinformation_container_ntpcontainer, 71);
lv_obj_set_x( ui_timeinformation_container_ntpcontainer, 4 );
lv_obj_set_y( ui_timeinformation_container_ntpcontainer, 77 );
lv_obj_set_align( ui_timeinformation_container_ntpcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timeinformation_container_ntpcontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timeinformation_container_ntpcontainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_timeinformation_container_ntpcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeinformation_textarea_ntpinput = lv_textarea_create(ui_timeinformation_container_ntpcontainer);
lv_obj_set_width( ui_timeinformation_textarea_ntpinput, 267);
lv_obj_set_height( ui_timeinformation_textarea_ntpinput, 42);
lv_obj_set_align( ui_timeinformation_textarea_ntpinput, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_timeinformation_textarea_ntpinput,"Input NTP Server");
lv_textarea_set_placeholder_text(ui_timeinformation_textarea_ntpinput,"Placeholder...");

ui_timeinformation_label_ntplabel = lv_label_create(ui_timeinformation_container_ntpcontainer);
lv_obj_set_width( ui_timeinformation_label_ntplabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeinformation_label_ntplabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_timeinformation_label_ntplabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeinformation_label_ntplabel,"NTP Server");
lv_obj_set_style_text_color(ui_timeinformation_label_ntplabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeinformation_label_ntplabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen_TimeInformation = ui_screen_timeinformation;
ui_BackGroundContainer6 = ui_timeinformation_backgroundcontainer_backgroundcontainer6;
ui_TimeInformation_Container_SyncButtonContainer = ui_timeinformation_container_syncbuttoncontainer;
ui_TimeInformation_Button_syncButton = ui_timeinformation_button_syncbutton;
ui_TimeInformation_Label_SyncIcon = ui_timeinformation_label_syncicon;
ui_TimeInformation_Label_SyncNow = ui_timeinformation_label_syncnow;
ui_TimeInformation_Container_MasterTimeContainer = ui_timeinformation_container_mastertimecontainer;
ui_TimeInformation_Container_TimeInfoContainer = ui_timeinformation_container_timeinfocontainer;
ui_TimeInformation_Dropdown_AMPM = ui_timeinformation_dropdown_ampm;
ui_TimeInformation_Label_TimeInfoLabel = ui_timeinformation_label_timeinfolabel;
ui_TimeInformation_Container_TimeZoneContainer = ui_timeinformation_container_timezonecontainer;
ui_TimeInformation_Dropdown_TimeZone = ui_timeinformation_dropdown_timezone;

}

void ui_screen_timeinformation_screen_destroy(void)
{
   if (ui_screen_timeinformation) lv_obj_del(ui_screen_timeinformation);

// NULL screen variables
ui_Screen_TimeInformation= NULL;
ui_screen_timeinformation= NULL;
ui_BackGroundContainer6= NULL;
ui_timeinformation_backgroundcontainer_backgroundcontainer6= NULL;
ui_TimeInformation_Container_SyncButtonContainer= NULL;
ui_timeinformation_container_syncbuttoncontainer= NULL;
ui_TimeInformation_Button_syncButton= NULL;
ui_timeinformation_button_syncbutton= NULL;
ui_TimeInformation_Label_SyncIcon= NULL;
ui_timeinformation_label_syncicon= NULL;
ui_TimeInformation_Label_SyncNow= NULL;
ui_timeinformation_label_syncnow= NULL;
ui_TimeInformation_Container_MasterTimeContainer= NULL;
ui_timeinformation_container_mastertimecontainer= NULL;
ui_TimeInformation_Container_TimeInfoContainer= NULL;
ui_timeinformation_container_timeinfocontainer= NULL;
ui_timeinformation_spinbox_timeinput= NULL;
ui_TimeInformation_Dropdown_AMPM= NULL;
ui_timeinformation_dropdown_ampm= NULL;
ui_TimeInformation_Label_TimeInfoLabel= NULL;
ui_timeinformation_label_timeinfolabel= NULL;
ui_timeinformation_container_mastertimezonecontainer= NULL;
ui_TimeInformation_Container_TimeZoneContainer= NULL;
ui_timeinformation_container_timezonecontainer= NULL;
ui_TimeInformation_Dropdown_TimeZone= NULL;
ui_timeinformation_dropdown_timezone= NULL;
ui_timeinformation_label_timezonelabel= NULL;
ui_timeinformation_container_ntpcontainer= NULL;
ui_timeinformation_textarea_ntpinput= NULL;
ui_timeinformation_label_ntplabel= NULL;

}
