// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_DEVICEINFORMATION_H
#define UI_SCREEN_DEVICEINFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_deviceinformation
extern void ui_screen_deviceinformation_screen_init(void);
extern void ui_screen_deviceinformation_screen_destroy(void);
extern lv_obj_t *ui_screen_deviceinformation;
extern lv_obj_t *ui_deviceinformation_backgroundcontainer_backgroundcontainer1;
extern lv_obj_t *ui_deviceinformation_container_headercontainer;
extern lv_obj_t *ui_deviceinformation_label_deviceinfocontainer;
extern lv_obj_t *ui_deviceinformation_container_devicedisplaytypecontainer;
extern lv_obj_t *ui_deviceinformation_button_harwarebutton;
extern lv_obj_t *ui_deviceinformation_label_hardwarelabel;
extern lv_obj_t *ui_deviceinformation_button_softwarebutton;
extern lv_obj_t *ui_deviceinformation_label_softwarelabel;
extern lv_obj_t *ui_deviceinformation_container_informationarea;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_DeviceInformation;
extern lv_obj_t *ui_DeviceInformation_BackGroundContainer_BackGroundContainer1;
extern lv_obj_t *ui_DeviceInformation_Container_HeaderContainer;
extern lv_obj_t *ui_DeviceInformation_Label_DeviceInfoContainer;
extern lv_obj_t *ui_DeviceInformation_Container_DeviceDisplayTypeContainer;
extern lv_obj_t *ui_DeviceInformation_Button_HarwareButton;
extern lv_obj_t *ui_DeviceInformation_Label_HardwareLabel;
extern lv_obj_t *ui_DeviceInformation_Button_SoftwareButton;
extern lv_obj_t *ui_DeviceInformation_Label_SoftwareLabel;
extern lv_obj_t *ui_DeviceInformation_Container_InformationArea;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

