// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "ui.h"

lv_obj_t *ui_MainScreen_Label_SettingsButtonLabel;
lv_obj_t *ui_MainScreen_Button_SettingsButton;
lv_obj_t *ui_MainScreen_Container_bottombarcontainer;
lv_obj_t *ui_MainScreen_Label_datelabel;
lv_obj_t *ui_MainScreen_Label_timelabel;
lv_obj_t *ui_MainScreen_Container_grouprightContainer;
lv_obj_t *ui_MainScreen_Label_machinenamelabel;
lv_obj_t *ui_MainScreen_Label_BluetoothIconlabel;
lv_obj_t *ui_MainScreen_Label_neticonlabel;
lv_obj_t *ui_MainScreen_Container_groupLeftContainer;
lv_obj_t *ui_MainScreen_Container_topbarContainer;
lv_obj_t *ui_MainScreen_BackGroundContainer_BackGroundContainer2;
lv_obj_t *ui_Screen_MainScreen;
lv_obj_t *ui_screen_mainscreen = NULL;lv_obj_t *ui_mainscreen_backgroundcontainer_backgroundcontainer2 = NULL;lv_obj_t *ui_mainscreen_container_topbarcontainer = NULL;lv_obj_t *ui_mainscreen_container_groupleftcontainer = NULL;lv_obj_t *ui_mainscreen_label_neticonlabel = NULL;lv_obj_t *ui_mainscreen_label_bluetoothiconlabel = NULL;lv_obj_t *ui_mainscreen_label_machinenamelabel = NULL;lv_obj_t *ui_mainscreen_container_grouprightcontainer = NULL;lv_obj_t *ui_mainscreen_label_timelabel = NULL;lv_obj_t *ui_mainscreen_label_datelabel = NULL;lv_obj_t *ui_mainscreen_container_bottombarcontainer = NULL;lv_obj_t *ui_mainscreen_button_settingsbutton = NULL;lv_obj_t *ui_mainscreen_label_settingsbuttonlabel = NULL;
// event funtions
void ui_event_mainscreen_label_neticonlabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_mainscreen_label_neticonlabel, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
}
}

void ui_event_mainscreen_button_settingsbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_adminlogin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_adminlogin_screen_init);
}
}

// build funtions

void ui_screen_mainscreen_screen_init(void)
{
ui_screen_mainscreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_mainscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_screen_mainscreen, lv_color_hex(0xEA0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_screen_mainscreen, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_backgroundcontainer_backgroundcontainer2 = ui_container_backgroundcontainer_create(ui_screen_mainscreen);
lv_obj_set_x( ui_mainscreen_backgroundcontainer_backgroundcontainer2, 0 );
lv_obj_set_y( ui_mainscreen_backgroundcontainer_backgroundcontainer2, 0 );

ui_mainscreen_container_topbarcontainer = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_topbarcontainer);
lv_obj_set_width( ui_mainscreen_container_topbarcontainer, 1024);
lv_obj_set_height( ui_mainscreen_container_topbarcontainer, 60);
lv_obj_set_flex_flow(ui_mainscreen_container_topbarcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_topbarcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_topbarcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen_container_topbarcontainer, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen_container_topbarcontainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_mainscreen_container_topbarcontainer, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainscreen_container_topbarcontainer, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainscreen_container_topbarcontainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainscreen_container_topbarcontainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_groupleftcontainer = lv_obj_create(ui_mainscreen_container_topbarcontainer);
lv_obj_remove_style_all(ui_mainscreen_container_groupleftcontainer);
lv_obj_set_width( ui_mainscreen_container_groupleftcontainer, 80);
lv_obj_set_height( ui_mainscreen_container_groupleftcontainer, 60);
lv_obj_set_align( ui_mainscreen_container_groupleftcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_container_groupleftcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_groupleftcontainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_groupleftcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainscreen_label_neticonlabel = lv_label_create(ui_mainscreen_container_groupleftcontainer);
lv_obj_set_width( ui_mainscreen_label_neticonlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_neticonlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_neticonlabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_mainscreen_label_neticonlabel,"");
lv_obj_remove_flag( ui_mainscreen_label_neticonlabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_mainscreen_label_neticonlabel, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_neticonlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_neticonlabel, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_mainscreen_label_neticonlabel, lv_color_hex(0x00C853), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_mainscreen_label_neticonlabel, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_mainscreen_label_neticonlabel, &ui_font_Icons, LV_PART_MAIN| LV_STATE_USER_1);

ui_mainscreen_label_bluetoothiconlabel = lv_label_create(ui_mainscreen_container_groupleftcontainer);
lv_obj_set_width( ui_mainscreen_label_bluetoothiconlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_bluetoothiconlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainscreen_label_bluetoothiconlabel, 55 );
lv_obj_set_y( ui_mainscreen_label_bluetoothiconlabel, 4 );
lv_obj_set_align( ui_mainscreen_label_bluetoothiconlabel, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_mainscreen_label_bluetoothiconlabel,"");
lv_obj_set_style_text_font(ui_mainscreen_label_bluetoothiconlabel, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_machinenamelabel = lv_label_create(ui_mainscreen_container_topbarcontainer);
lv_obj_set_width( ui_mainscreen_label_machinenamelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_machinenamelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_machinenamelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainscreen_label_machinenamelabel,"MACHINE-001");
lv_obj_set_style_text_color(ui_mainscreen_label_machinenamelabel, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_machinenamelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_machinenamelabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_grouprightcontainer = lv_obj_create(ui_mainscreen_container_topbarcontainer);
lv_obj_remove_style_all(ui_mainscreen_container_grouprightcontainer);
lv_obj_set_width( ui_mainscreen_container_grouprightcontainer, 100);
lv_obj_set_height( ui_mainscreen_container_grouprightcontainer, 60);
lv_obj_set_align( ui_mainscreen_container_grouprightcontainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_container_grouprightcontainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_mainscreen_container_grouprightcontainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_mainscreen_container_grouprightcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainscreen_label_timelabel = lv_label_create(ui_mainscreen_container_grouprightcontainer);
lv_obj_set_width( ui_mainscreen_label_timelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_timelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_timelabel, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_mainscreen_label_timelabel,"2:34 PM");
lv_obj_set_style_text_color(ui_mainscreen_label_timelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_timelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_timelabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_datelabel = lv_label_create(ui_mainscreen_container_grouprightcontainer);
lv_obj_set_width( ui_mainscreen_label_datelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_datelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_datelabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_mainscreen_label_datelabel,"2025-10-19");
lv_obj_set_style_text_color(ui_mainscreen_label_datelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_datelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_datelabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_bottombarcontainer = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_bottombarcontainer);
lv_obj_set_width( ui_mainscreen_container_bottombarcontainer, 1024);
lv_obj_set_height( ui_mainscreen_container_bottombarcontainer, 60);
lv_obj_set_align( ui_mainscreen_container_bottombarcontainer, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_mainscreen_container_bottombarcontainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_bottombarcontainer, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_bottombarcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_mainscreen_container_bottombarcontainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainscreen_container_bottombarcontainer, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainscreen_container_bottombarcontainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainscreen_container_bottombarcontainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_button_settingsbutton = lv_button_create(ui_mainscreen_container_bottombarcontainer);
lv_obj_set_width( ui_mainscreen_button_settingsbutton, 60);
lv_obj_set_height( ui_mainscreen_button_settingsbutton, 50);
lv_obj_set_x( ui_mainscreen_button_settingsbutton, 37 );
lv_obj_set_y( ui_mainscreen_button_settingsbutton, 0 );
lv_obj_set_align( ui_mainscreen_button_settingsbutton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_button_settingsbutton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_button_settingsbutton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_mainscreen_button_settingsbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_mainscreen_button_settingsbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen_button_settingsbutton, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen_button_settingsbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_settingsbuttonlabel = lv_label_create(ui_mainscreen_button_settingsbutton);
lv_obj_set_width( ui_mainscreen_label_settingsbuttonlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_settingsbuttonlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_settingsbuttonlabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_label_settingsbuttonlabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_label_settingsbuttonlabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_mainscreen_label_settingsbuttonlabel,"");
lv_obj_set_style_text_font(ui_mainscreen_label_settingsbuttonlabel, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_mainscreen_label_neticonlabel, ui_event_mainscreen_label_neticonlabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mainscreen_button_settingsbutton, ui_event_mainscreen_button_settingsbutton, LV_EVENT_ALL, NULL);
ui_Screen_MainScreen = ui_screen_mainscreen;
ui_MainScreen_BackGroundContainer_BackGroundContainer2 = ui_mainscreen_backgroundcontainer_backgroundcontainer2;
ui_MainScreen_Container_topbarContainer = ui_mainscreen_container_topbarcontainer;
ui_MainScreen_Container_groupLeftContainer = ui_mainscreen_container_groupleftcontainer;
ui_MainScreen_Label_neticonlabel = ui_mainscreen_label_neticonlabel;
ui_MainScreen_Label_BluetoothIconlabel = ui_mainscreen_label_bluetoothiconlabel;
ui_MainScreen_Label_machinenamelabel = ui_mainscreen_label_machinenamelabel;
ui_MainScreen_Container_grouprightContainer = ui_mainscreen_container_grouprightcontainer;
ui_MainScreen_Label_timelabel = ui_mainscreen_label_timelabel;
ui_MainScreen_Label_datelabel = ui_mainscreen_label_datelabel;
ui_MainScreen_Container_bottombarcontainer = ui_mainscreen_container_bottombarcontainer;
ui_MainScreen_Button_SettingsButton = ui_mainscreen_button_settingsbutton;
ui_MainScreen_Label_SettingsButtonLabel = ui_mainscreen_label_settingsbuttonlabel;

}

void ui_screen_mainscreen_screen_destroy(void)
{
   if (ui_screen_mainscreen) lv_obj_del(ui_screen_mainscreen);

// NULL screen variables
ui_Screen_MainScreen= NULL;
ui_screen_mainscreen= NULL;
ui_MainScreen_BackGroundContainer_BackGroundContainer2= NULL;
ui_mainscreen_backgroundcontainer_backgroundcontainer2= NULL;
ui_MainScreen_Container_topbarContainer= NULL;
ui_mainscreen_container_topbarcontainer= NULL;
ui_MainScreen_Container_groupLeftContainer= NULL;
ui_mainscreen_container_groupleftcontainer= NULL;
ui_MainScreen_Label_neticonlabel= NULL;
ui_mainscreen_label_neticonlabel= NULL;
ui_MainScreen_Label_BluetoothIconlabel= NULL;
ui_mainscreen_label_bluetoothiconlabel= NULL;
ui_MainScreen_Label_machinenamelabel= NULL;
ui_mainscreen_label_machinenamelabel= NULL;
ui_MainScreen_Container_grouprightContainer= NULL;
ui_mainscreen_container_grouprightcontainer= NULL;
ui_MainScreen_Label_timelabel= NULL;
ui_mainscreen_label_timelabel= NULL;
ui_MainScreen_Label_datelabel= NULL;
ui_mainscreen_label_datelabel= NULL;
ui_MainScreen_Container_bottombarcontainer= NULL;
ui_mainscreen_container_bottombarcontainer= NULL;
ui_MainScreen_Button_SettingsButton= NULL;
ui_mainscreen_button_settingsbutton= NULL;
ui_MainScreen_Label_SettingsButtonLabel= NULL;
ui_mainscreen_label_settingsbuttonlabel= NULL;

}
