// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_WIFISETUP_H
#define UI_SCREEN_WIFISETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_wifisetup
extern void ui_screen_wifisetup_screen_init(void);
extern void ui_screen_wifisetup_screen_destroy(void);
extern lv_obj_t *ui_screen_wifisetup;
extern lv_obj_t *ui_wifisetup_backgroundcontainer_backgroundcontainer4;
extern lv_obj_t *ui_wifisetup_container_settingsenclosurecontainer;
extern lv_obj_t *ui_wifisetup_container_infoheadercontainer;
extern lv_obj_t *ui_wifisetup_label_lblwificonfig;
extern lv_obj_t *ui_wifisetup_label_wifidisconnected;
extern lv_obj_t *ui_wifisetup_container_ssidcontainer;
extern lv_obj_t *ui_wifisetup_label_ssidlabel;
extern void ui_event_wifisetup_textarea_ssidinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_ssidinput;
extern lv_obj_t *ui_wifisetup_container_passwordcontainer;
extern lv_obj_t *ui_wifisetup_label_passwordlabel;
extern void ui_event_wifisetup_textarea_passwordinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_passwordinput;
extern lv_obj_t *ui_wifisetup_container_hostnamecontainer;
extern lv_obj_t *ui_wifisetup_label_hostnamelabel;
extern void ui_event_wifisetup_textarea_hostnameinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_hostnameinput;
extern lv_obj_t *ui_wifisetup_container_dhcpcontrolcontainer;
extern lv_obj_t *ui_wifisetup_label_dhcpcontrollabel;
extern void ui_event_wifisetup_switch_dhcpswitch( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_switch_dhcpswitch;
extern lv_obj_t *ui_wifisetup_container_manualipsettingscontainer;
extern lv_obj_t *ui_wifisetup_container_ipaddresscontainer;
extern lv_obj_t *ui_wifisetup_label_ipaddresslabel;
extern void ui_event_wifisetup_textarea_ipaddressinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_ipaddressinput;
extern lv_obj_t *ui_wifisetup_container_gatewaycontainer;
extern lv_obj_t *ui_wifisetup_label_gatewaylabel;
extern void ui_event_wifisetup_textarea_gatewayinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_gatewayinput;
extern lv_obj_t *ui_wifisetup_container_netmaskcontainer;
extern lv_obj_t *ui_wifisetup_label_netmasklabel;
extern void ui_event_wifisetup_textarea_netmaskinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_netmaskinput;
extern lv_obj_t *ui_wifisetup_container_dnscontainer;
extern lv_obj_t *ui_wifisetup_label_dnslabel;
extern void ui_event_wifisetup_textarea_dnsinput( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_dnsinput;
extern lv_obj_t *ui_wifisetup_container_dns2container;
extern lv_obj_t *ui_wifisetup_label_dns2label;
extern void ui_event_wifisetup_textarea_dns2input( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_textarea_dns2input;
extern void ui_event_wifisetup_keyboard_networkkeyboard( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_keyboard_networkkeyboard;
extern lv_obj_t *ui_wifisetup_container_cancelok;
extern void ui_event_wifisetup_button_cancelbutton( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_button_cancelbutton;
extern lv_obj_t *ui_wifisetup_label_cancellabel;
extern void ui_event_wifisetup_button_okbutton( lv_event_t * e);
extern lv_obj_t *ui_wifisetup_button_okbutton;
extern lv_obj_t *ui_wifisetup_label_oklabel;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen_WiFiSetup;
extern lv_obj_t *ui_WiFiSetup_BackGroundContainer_BackGroundContainer4;
extern lv_obj_t *ui_WiFiSetup_Container_SettingsEnclosureContainer;
extern lv_obj_t *ui_WiFiSetup_Container_InfoHeaderContainer;
extern lv_obj_t *ui_WiFiSetup_Label_lblWifiConfig;
extern lv_obj_t *ui_WiFiSetup_Label_WiFiDisconnected;
extern lv_obj_t *ui_WiFiSetup_Container_ssidContainer;
extern lv_obj_t *ui_WiFiSetup_Label_SSIDLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_ssidInput;
extern lv_obj_t *ui_WiFiSetup_Container_PasswordContainer;
extern lv_obj_t *ui_WiFiSetup_Label_PasswordLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_PasswordInput;
extern lv_obj_t *ui_WiFiSetup_Container_HostnameContainer;
extern lv_obj_t *ui_WiFiSetup_Label_HostnameLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_HostnameInput;
extern lv_obj_t *ui_WiFiSetup_Container_DhcpControlContainer;
extern lv_obj_t *ui_WiFiSetup_Label_DhcpControlLabel;
extern lv_obj_t *ui_WiFiSetup_Switch_DHCPSwitch;
extern lv_obj_t *ui_WiFiSetup_Container_ManualIPSettingsContainer;
extern lv_obj_t *ui_WiFiSetup_Container_ipAddressContainer;
extern lv_obj_t *ui_WiFiSetup_Label_ipAddressLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_ipAddressInput;
extern lv_obj_t *ui_WiFiSetup_Container_GatewayContainer;
extern lv_obj_t *ui_WiFiSetup_Label_GatewayLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_GatewayInput;
extern lv_obj_t *ui_WiFiSetup_Container_NetMaskContainer;
extern lv_obj_t *ui_WiFiSetup_Label_NetMaskLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_NetMaskInput;
extern lv_obj_t *ui_WiFiSetup_Container_DNSContainer;
extern lv_obj_t *ui_WiFiSetup_Label_DNSLabel;
extern lv_obj_t *ui_WiFiSetup_Textarea_DNSInput;
extern lv_obj_t *ui_WiFiSetup_Container_DNS2Container;
extern lv_obj_t *ui_WiFiSetup_Label_DNS2Label;
extern lv_obj_t *ui_WiFiSetup_Textarea_DNS2Input;
extern lv_obj_t *ui_WiFiSetup_Keyboard_NetworkKeyboard;
extern lv_obj_t *ui_WiFiSetup_Button_CancelButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

