// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#include "../ui.h"

lv_obj_t *ui_MainScreen_Keyboard_uikeyboard;
lv_obj_t *ui_MainScreen_Textarea_uitxtdevicename;
lv_obj_t *ui_MainScreen_Container_uinetworkinputcontainer;
lv_obj_t *ui_MainScreen_Label_SettingsButtonLabel;
lv_obj_t *ui_MainScreen_Button_SettingsButton;
lv_obj_t *ui_MainScreen_Container_bottombar;
lv_obj_t *ui_MainScreen_Label_lbldate;
lv_obj_t *ui_MainScreen_Label_lbltime;
lv_obj_t *ui_MainScreen_Container_groupright;
lv_obj_t *ui_MainScreen_Label_lblmachinename;
lv_obj_t *ui_MainScreen_Label_BluetoothIcon;
lv_obj_t *ui_MainScreen_Label_lblneticon;
lv_obj_t *ui_MainScreen_Container_groupleft;
lv_obj_t *ui_MainScreen_Container_topbar;
lv_obj_t *ui_Screen1_Container_BackGround;
lv_obj_t *ui_screen_mainscreen = NULL;lv_obj_t *ui_mainscreen_container_background = NULL;lv_obj_t *ui_mainscreen_container_topbar = NULL;lv_obj_t *ui_mainscreen_container_groupleft = NULL;lv_obj_t *ui_mainscreen_label_lblneticon = NULL;lv_obj_t *ui_mainscreen_label_bluetoothicon = NULL;lv_obj_t *ui_mainscreen_label_lblmachinename = NULL;lv_obj_t *ui_mainscreen_container_groupright = NULL;lv_obj_t *ui_mainscreen_label_lbltime = NULL;lv_obj_t *ui_mainscreen_label_lbldate = NULL;lv_obj_t *ui_mainscreen_container_bottombar = NULL;lv_obj_t *ui_mainscreen_button_settingsbutton = NULL;lv_obj_t *ui_mainscreen_label_settingsbuttonlabel = NULL;lv_obj_t *ui_mainscreen_container_uinetworkinputcontainer = NULL;lv_obj_t *ui_mainscreen_textarea_uitxtdevicename = NULL;lv_obj_t *ui_mainscreen_keyboard_uikeyboard = NULL;
// event funtions
void ui_event_mainscreen_label_lblneticon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_mainscreen_label_lblneticon, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
}
}

void ui_event_mainscreen_textarea_uitxtdevicename( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_mainscreen_keyboard_uikeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      ui_link_keyboard_to_device_name( e );
}
}

void ui_event_mainscreen_keyboard_uikeyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_mainscreen_keyboard_uikeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CANCEL) {
      _ui_flag_modify( ui_mainscreen_keyboard_uikeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_screen_mainscreen_screen_init(void)
{
ui_screen_mainscreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_mainscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_screen_mainscreen, lv_color_hex(0xEA0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_screen_mainscreen, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_background = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_background);
lv_obj_set_width( ui_mainscreen_container_background, 1024);
lv_obj_set_height( ui_mainscreen_container_background, 600);
lv_obj_set_align( ui_mainscreen_container_background, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_mainscreen_container_background, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen_container_background, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen_container_background, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_topbar = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_topbar);
lv_obj_set_width( ui_mainscreen_container_topbar, 1024);
lv_obj_set_height( ui_mainscreen_container_topbar, 60);
lv_obj_set_flex_flow(ui_mainscreen_container_topbar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_topbar, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_topbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen_container_topbar, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen_container_topbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_mainscreen_container_topbar, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainscreen_container_topbar, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainscreen_container_topbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainscreen_container_topbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_groupleft = lv_obj_create(ui_mainscreen_container_topbar);
lv_obj_remove_style_all(ui_mainscreen_container_groupleft);
lv_obj_set_width( ui_mainscreen_container_groupleft, 100);
lv_obj_set_height( ui_mainscreen_container_groupleft, 60);
lv_obj_set_align( ui_mainscreen_container_groupleft, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_container_groupleft,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_groupleft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_groupleft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainscreen_label_lblneticon = lv_label_create(ui_mainscreen_container_groupleft);
lv_obj_set_width( ui_mainscreen_label_lblneticon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_lblneticon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_lblneticon, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_mainscreen_label_lblneticon,"");
lv_obj_remove_flag( ui_mainscreen_label_lblneticon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_mainscreen_label_lblneticon, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_lblneticon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_lblneticon, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_mainscreen_label_lblneticon, lv_color_hex(0x00C853), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_mainscreen_label_lblneticon, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_mainscreen_label_lblneticon, &ui_font_Icons, LV_PART_MAIN| LV_STATE_USER_1);

ui_mainscreen_label_bluetoothicon = lv_label_create(ui_mainscreen_container_groupleft);
lv_obj_set_width( ui_mainscreen_label_bluetoothicon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_bluetoothicon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_bluetoothicon, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainscreen_label_bluetoothicon,"");
lv_obj_set_style_text_font(ui_mainscreen_label_bluetoothicon, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_lblmachinename = lv_label_create(ui_mainscreen_container_topbar);
lv_obj_set_width( ui_mainscreen_label_lblmachinename, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_lblmachinename, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_lblmachinename, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainscreen_label_lblmachinename,"MACHINE-001");
lv_obj_set_style_text_color(ui_mainscreen_label_lblmachinename, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_lblmachinename, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_lblmachinename, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_groupright = lv_obj_create(ui_mainscreen_container_topbar);
lv_obj_remove_style_all(ui_mainscreen_container_groupright);
lv_obj_set_width( ui_mainscreen_container_groupright, 100);
lv_obj_set_height( ui_mainscreen_container_groupright, 60);
lv_obj_set_align( ui_mainscreen_container_groupright, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_container_groupright,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_mainscreen_container_groupright, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_mainscreen_container_groupright, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainscreen_label_lbltime = lv_label_create(ui_mainscreen_container_groupright);
lv_obj_set_width( ui_mainscreen_label_lbltime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_lbltime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_lbltime, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_mainscreen_label_lbltime,"2:34 PM");
lv_obj_set_style_text_color(ui_mainscreen_label_lbltime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_lbltime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_lbltime, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_lbldate = lv_label_create(ui_mainscreen_container_groupright);
lv_obj_set_width( ui_mainscreen_label_lbldate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_lbldate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_lbldate, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_mainscreen_label_lbldate,"2025-10-19");
lv_obj_set_style_text_color(ui_mainscreen_label_lbldate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen_label_lbldate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainscreen_label_lbldate, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_bottombar = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_bottombar);
lv_obj_set_width( ui_mainscreen_container_bottombar, 1024);
lv_obj_set_height( ui_mainscreen_container_bottombar, 50);
lv_obj_set_align( ui_mainscreen_container_bottombar, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_mainscreen_container_bottombar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_container_bottombar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_mainscreen_container_bottombar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_mainscreen_container_bottombar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainscreen_container_bottombar, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainscreen_container_bottombar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainscreen_container_bottombar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_button_settingsbutton = lv_button_create(ui_mainscreen_container_bottombar);
lv_obj_set_width( ui_mainscreen_button_settingsbutton, 60);
lv_obj_set_height( ui_mainscreen_button_settingsbutton, 50);
lv_obj_set_align( ui_mainscreen_button_settingsbutton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_button_settingsbutton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_button_settingsbutton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_mainscreen_button_settingsbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_mainscreen_button_settingsbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen_button_settingsbutton, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen_button_settingsbutton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_label_settingsbuttonlabel = lv_label_create(ui_mainscreen_button_settingsbutton);
lv_obj_set_width( ui_mainscreen_label_settingsbuttonlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainscreen_label_settingsbuttonlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mainscreen_label_settingsbuttonlabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mainscreen_label_settingsbuttonlabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mainscreen_label_settingsbuttonlabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_mainscreen_label_settingsbuttonlabel,"");
lv_obj_set_style_text_font(ui_mainscreen_label_settingsbuttonlabel, &ui_font_Icons, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_container_uinetworkinputcontainer = lv_obj_create(ui_screen_mainscreen);
lv_obj_remove_style_all(ui_mainscreen_container_uinetworkinputcontainer);
lv_obj_set_width( ui_mainscreen_container_uinetworkinputcontainer, 604);
lv_obj_set_height( ui_mainscreen_container_uinetworkinputcontainer, 318);
lv_obj_set_x( ui_mainscreen_container_uinetworkinputcontainer, -26 );
lv_obj_set_y( ui_mainscreen_container_uinetworkinputcontainer, 62 );
lv_obj_set_align( ui_mainscreen_container_uinetworkinputcontainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_mainscreen_container_uinetworkinputcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainscreen_textarea_uitxtdevicename = lv_textarea_create(ui_mainscreen_container_uinetworkinputcontainer);
lv_obj_set_width( ui_mainscreen_textarea_uitxtdevicename, 309);
lv_obj_set_height( ui_mainscreen_textarea_uitxtdevicename, 70);
lv_obj_set_x( ui_mainscreen_textarea_uitxtdevicename, -104 );
lv_obj_set_y( ui_mainscreen_textarea_uitxtdevicename, -95 );
lv_obj_set_align( ui_mainscreen_textarea_uitxtdevicename, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_mainscreen_textarea_uitxtdevicename,"Placeholder...");
lv_obj_set_style_text_font(ui_mainscreen_textarea_uitxtdevicename, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainscreen_keyboard_uikeyboard = lv_keyboard_create(ui_mainscreen_container_uinetworkinputcontainer);
lv_obj_set_width( ui_mainscreen_keyboard_uikeyboard, 530);
lv_obj_set_height( ui_mainscreen_keyboard_uikeyboard, 178);
lv_obj_set_x( ui_mainscreen_keyboard_uikeyboard, 18 );
lv_obj_set_y( ui_mainscreen_keyboard_uikeyboard, 20 );
lv_obj_set_align( ui_mainscreen_keyboard_uikeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mainscreen_keyboard_uikeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_mainscreen_label_lblneticon, ui_event_mainscreen_label_lblneticon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mainscreen_textarea_uitxtdevicename, ui_event_mainscreen_textarea_uitxtdevicename, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mainscreen_keyboard_uikeyboard, ui_event_mainscreen_keyboard_uikeyboard, LV_EVENT_ALL, NULL);
ui_Screen1_Container_BackGround = ui_mainscreen_container_background;
ui_MainScreen_Container_topbar = ui_mainscreen_container_topbar;
ui_MainScreen_Container_groupleft = ui_mainscreen_container_groupleft;
ui_MainScreen_Label_lblneticon = ui_mainscreen_label_lblneticon;
ui_MainScreen_Label_BluetoothIcon = ui_mainscreen_label_bluetoothicon;
ui_MainScreen_Label_lblmachinename = ui_mainscreen_label_lblmachinename;
ui_MainScreen_Container_groupright = ui_mainscreen_container_groupright;
ui_MainScreen_Label_lbltime = ui_mainscreen_label_lbltime;
ui_MainScreen_Label_lbldate = ui_mainscreen_label_lbldate;
ui_MainScreen_Container_bottombar = ui_mainscreen_container_bottombar;
ui_MainScreen_Button_SettingsButton = ui_mainscreen_button_settingsbutton;
ui_MainScreen_Label_SettingsButtonLabel = ui_mainscreen_label_settingsbuttonlabel;
ui_MainScreen_Container_uinetworkinputcontainer = ui_mainscreen_container_uinetworkinputcontainer;
ui_MainScreen_Textarea_uitxtdevicename = ui_mainscreen_textarea_uitxtdevicename;
ui_MainScreen_Keyboard_uikeyboard = ui_mainscreen_keyboard_uikeyboard;

}

void ui_screen_mainscreen_screen_destroy(void)
{
   if (ui_screen_mainscreen) lv_obj_del(ui_screen_mainscreen);

// NULL screen variables
ui_screen_mainscreen= NULL;
ui_Screen1_Container_BackGround= NULL;
ui_mainscreen_container_background= NULL;
ui_MainScreen_Container_topbar= NULL;
ui_mainscreen_container_topbar= NULL;
ui_MainScreen_Container_groupleft= NULL;
ui_mainscreen_container_groupleft= NULL;
ui_MainScreen_Label_lblneticon= NULL;
ui_mainscreen_label_lblneticon= NULL;
ui_MainScreen_Label_BluetoothIcon= NULL;
ui_mainscreen_label_bluetoothicon= NULL;
ui_MainScreen_Label_lblmachinename= NULL;
ui_mainscreen_label_lblmachinename= NULL;
ui_MainScreen_Container_groupright= NULL;
ui_mainscreen_container_groupright= NULL;
ui_MainScreen_Label_lbltime= NULL;
ui_mainscreen_label_lbltime= NULL;
ui_MainScreen_Label_lbldate= NULL;
ui_mainscreen_label_lbldate= NULL;
ui_MainScreen_Container_bottombar= NULL;
ui_mainscreen_container_bottombar= NULL;
ui_MainScreen_Button_SettingsButton= NULL;
ui_mainscreen_button_settingsbutton= NULL;
ui_MainScreen_Label_SettingsButtonLabel= NULL;
ui_mainscreen_label_settingsbuttonlabel= NULL;
ui_MainScreen_Container_uinetworkinputcontainer= NULL;
ui_mainscreen_container_uinetworkinputcontainer= NULL;
ui_MainScreen_Textarea_uitxtdevicename= NULL;
ui_mainscreen_textarea_uitxtdevicename= NULL;
ui_MainScreen_Keyboard_uikeyboard= NULL;
ui_mainscreen_keyboard_uikeyboard= NULL;

}
