// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_TimeClock_Rand

#ifndef UI_SCREEN_MAINSCREEN_H
#define UI_SCREEN_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_mainscreen
extern void ui_screen_mainscreen_screen_init(void);
extern void ui_screen_mainscreen_screen_destroy(void);
extern lv_obj_t *ui_screen_mainscreen;
extern lv_obj_t *ui_mainscreen_container_background;
extern lv_obj_t *ui_mainscreen_container_topbar;
extern lv_obj_t *ui_mainscreen_container_groupleft;
extern void ui_event_mainscreen_label_lblneticon( lv_event_t * e);
extern lv_obj_t *ui_mainscreen_label_lblneticon;
extern lv_obj_t *ui_mainscreen_label_bluetoothicon;
extern lv_obj_t *ui_mainscreen_label_lblmachinename;
extern lv_obj_t *ui_mainscreen_container_groupright;
extern lv_obj_t *ui_mainscreen_label_lbltime;
extern lv_obj_t *ui_mainscreen_label_lbldate;
extern lv_obj_t *ui_mainscreen_container_bottombar;
extern lv_obj_t *ui_mainscreen_button_settingsbutton;
extern lv_obj_t *ui_mainscreen_label_settingsbuttonlabel;
extern lv_obj_t *ui_mainscreen_container_uinetworkinputcontainer;
extern void ui_event_mainscreen_textarea_uitxtdevicename( lv_event_t * e);
extern lv_obj_t *ui_mainscreen_textarea_uitxtdevicename;
extern void ui_event_mainscreen_keyboard_uikeyboard( lv_event_t * e);
extern lv_obj_t *ui_mainscreen_keyboard_uikeyboard;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen1_Container_BackGround;
extern lv_obj_t *ui_MainScreen_Container_topbar;
extern lv_obj_t *ui_MainScreen_Container_groupleft;
extern lv_obj_t *ui_MainScreen_Label_lblneticon;
extern lv_obj_t *ui_MainScreen_Label_BluetoothIcon;
extern lv_obj_t *ui_MainScreen_Label_lblmachinename;
extern lv_obj_t *ui_MainScreen_Container_groupright;
extern lv_obj_t *ui_MainScreen_Label_lbltime;
extern lv_obj_t *ui_MainScreen_Label_lbldate;
extern lv_obj_t *ui_MainScreen_Container_bottombar;
extern lv_obj_t *ui_MainScreen_Button_SettingsButton;
extern lv_obj_t *ui_MainScreen_Label_SettingsButtonLabel;
extern lv_obj_t *ui_MainScreen_Container_uinetworkinputcontainer;
extern lv_obj_t *ui_MainScreen_Textarea_uitxtdevicename;
extern lv_obj_t *ui_MainScreen_Keyboard_uikeyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

